### PR TITLE
Fixed local and webots URLs for proto editing

### PR DESCRIPTION
**Pull request by omichel**
Fixes the replacement of local URLs while editing remote protos, as spotted in #5003.

In addition, this PR also fixes a bug in the `webots://` replacement as `WbUrl::remoteWebotsAssetPrefix()` was used instead of the actual `repository/branch-tag-or-hash` URL.

### CODE REVIEW

**Comment by BenjaminDeleze** [comment]
It tested a bit for `Edit Proto node` and it seems to work.

However, there is still issues if you do:

- `Add node`
- Click on `Spot`
- `Export`
- Import local `Spot`

**Comment by omichel** [comment]
Radical solution: I removed the "Export" button from the Add Node dialog, as it was redundant with the "Edit PROTO" pop-up menu.

**Review by BenjaminDeleze — CHANGES_REQUESTED** [review]
I got some errors when trying to import a PROTO with the Supervisor but I am not sure it is related with this PR, I will continue testing tomorrow

**Review by BenjaminDeleze — APPROVED** [review]
Seems good to me

**Pull request merged**
