### PR TITLE
FLU: Convert Clearpath robots

### PR DESCRIPTION
**Pull request by lukicdarkoo**
- [x] (602) robots/clearpath/moose/protos/Moose.proto
- [x] (603) robots/clearpath/moose/protos/MooseWheel.proto
- [x] (604) robots/clearpath/pr2/protos/Pr2.proto
- [x] (236) projects/robots/clearpath/moose/worlds/moose_demo.wbt
- [x] (237) projects/robots/clearpath/pr2/worlds/pr2.wbt

### CODE REVIEW

**Review by BenjaminDeleze — CHANGES_REQUESTED** [review]
The moose seems all good, but when I open the PR2 I get a lot of errors:
```
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':886:27: error: Skipped unknown 'geometry' node or PROTO.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':1533:37: error: Skipped unknown 'geometry' field in Solid node.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':1959:79: error: Skipped unknown 'geometry' field in Solid node.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':2059:83: error: Skipped unknown 'geometry' node or PROTO.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':2385:37: error: Skipped unknown 'geometry' field in Solid node.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':2840:79: error: Skipped unknown 'geometry' field in Solid node.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':2940:83: error: Skipped unknown 'geometry' node or PROTO.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':886:27: error: Skipped unknown 'geometry' node or PROTO.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':2059:83: error: Skipped unknown 'geometry' node or PROTO.
ERROR: '/home/benjamin/webots2/projects/robots/clearpath/pr2/protos/Pr2.proto':2940:83: error: Skipped unknown 'geometry' node or PROTO.
```

Moreover it seems like the cameras and lidars are wrong

**Comment by lukicdarkoo** [comment]
All errors should be fixed.

Also, I will backport 9504d65d2d0df to master

**Review by BenjaminDeleze — APPROVED** [review]
Thank you!
It seems good to me but I ran the test suite to be sure as you changed the code. 
We should wait until it finished to merge

**Comment by lukicdarkoo** [comment]
The Windows failure is not related to this PR

**Pull request merged**
