### PR TITLE
Stop sending requests to motor if goal is canceled

### LINKED ISSUE #3381: Called cancelGoal but the remaining trajectory still executed
**Describe the Bug**
I developed another node to control `ur5e` in Webots using `/follow_joint_trajectory` interface. I wrote a callback function to monitor the determinant of Jacobian matrix computed by Moveit. If the trajectory is executing and the determinant is less than a threshold value, I will call `cancelGoal()` to prevent infinity joint velocity (i.e., singularity). But I found that, after `cancelGoal()` is called, the remaining trajectory still executed. I checked the code in [trajectory_follower.py](https://github.com/cyberbotics/webots/blob/master/projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/trajectory_follower.py) and I found that the `if ...` statement in Line  202 will not check if the goal is canceled.  Maybe `self.goal_handle is not None` should be added into the condition?

### PR DESCRIPTION
**Pull request by sean85914**
Fix #3381

### CODE REVIEW

**Review by omichel — DISMISSED** [review]
Thank you.

**Comment by omichel** [comment]
The tests are failing because the code is not PEP8 compliant:
> /home/runner/work/webots/webots/projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/trajectory_follower.py:202:129: E501: line too long (149 > 128 characters)

Can you please fix it?

**Review by omichel — APPROVED** [review]
Thanks.

**Comment by omichel** [comment]
@sean85914: you should now be able to press the "Squash and merge" button.

**Comment by sean85914** [comment]
@omichel  Thanks! Not familiar with CI so took lots of time to pass the test :rofl:

**Comment by omichel** [comment]
You also may install a PEP8 plugin in your local text editor, as explained [here](https://github.com/cyberbotics/webots/wiki/Python-Coding-Style).

**Pull request merged**
