### PR TITLE
Add one legged jumping robot

### PR DESCRIPTION
**Pull request by YuXianYuan**
I think this is a very interesting robot simulation model
Thanks for reading!!

### CODE REVIEW

**Comment by DavidMansolino** [comment]
@YuXianYuan thank you for your contribution, is your PR ready to be reviewed ?

**Comment by YuXianYuan** [comment]
yeap，any questions? 发自我的华为手机-------- 原始邮件 --------发件人： David Mansolino <notifications@github.com>日期： 2019年12月19日周四 下午4:51收件人： cyberbotics/webots <webots@noreply.github.com>抄送： XY_Yu_ <18813176186@163.com>, Mention <mention@noreply.github.com>主    题： Re: [cyberbotics/webots] Add one legged jumping robot (#1212)@YuXianYuan thank you for your contribution, is your PR ready to be reviewed ?

**Comment by YuXianYuan** [comment]
Today, I found the contributing guidelines, I decided to carefully modify my PR according to the contributing guidelines, sorry to disturb.  :D

**Comment by omichel** [comment]
Thank for you this contribution.
Could please translate to English all the comments that are written in Chinese in your source code?
We cannot accept to merge a contribution which is not fully written in English.
Of course, you can keep your Chinese name written in Chinese.

**Comment by omichel** [comment]
Also, please ensure the coding style is compliant with our specifications set forth here: https://github.com/cyberbotics/webots/wiki/C-Coding-Style

**Comment by YuXianYuan** [comment]
I am reading "contributing guidelines", and revising the next PR according to the guidelines.
This is my first time to use github and webots, and my English is not very good, I will try my best.
:D

**Comment by DavidMansolino** [comment]
Perfect, thank you!
Don't worry about the English do the best you can, we can always help you with English (but not with Chinese :wink: ).
Note that you can do the fixes in the same PR you don't need to create a new one.

**Pull request closed without merging**
