### PR TITLE
Merge revision into develop

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix conflicts:
* dependencies/Makefile.linux
* resources/web/wwi/Makefile
* src/packaging/webots_distro.c
* src/webots/launcher/webots-linux.sh

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
It's not ready yet.
I'm getting a crash after the extern test world.

**Comment by omichel** [comment]
OK, sorry... I will get back when it's ready.

**Comment by DavidMansolino** [comment]
I found the reason of the crash, but it sometimes rais on revision too, I will, therefore, port it back to revision too.

**Comment by DavidMansolino** [comment]
:+1: :heavy_check_mark:

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
:+1: (I created the PR so I cannot approve it)

**Pull request merged**
