### PR TITLE
Replaced references to master with released in documentation

### PR DESCRIPTION
**Pull request by omichel**
There were still many references to the master branch in the released documentation, which is wrong.
In particular the `js/viewer.js` was inviting people to edit the released documentation on the master branch, which is not what we want.
This PR fixes all these problems.

### CODE REVIEW

**Comment by omichel** [comment]
The test sources are failing due to mismatch in copyright date.

**Comment by stefaniapedrazzi** [comment]
`CONTRIBUTING.md` is still referring to the `master` branch for contribution to technical english writing: 
https://github.com/cyberbotics/webots/blame/released/CONTRIBUTING.md#L12

Would not also be better to link to the `released` branch so that users willing to do contributions will start directly from the correct branch?

> The test sources are failing due to mismatch in copyright date.
If we will have this issue every time we will run the documentation and sources tests on the `released` branch, then we should adjust the tests (in a different PR).

**Comment by omichel** [comment]
I just fixed the `CONTRIBUTING.md` file.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you

**Pull request merged**
