### PR TITLE
Extend Travis Tests.

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix Travis part of #1159

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Wiki updated: https://github.com/cyberbotics/webots/wiki/Continuous-Integration/_compare/967cfb6f799c62dbb87a936d7cdf2bba37f2c9c4...69101a72fca37a47cdac51a7a02ff294daaeae8b

**Comment by DavidMansolino** [comment]
:+1: :heavy_check_mark:

**Comment by stefaniapedrazzi** [comment]
What is exactly the difference between `travis_distrib` and `travis_release`?
It is not very clear to me when reading the wiki.

**Comment by DavidMansolino** [comment]
They do the same test but `travis_release` does not create the Github release.

**Comment by stefaniapedrazzi** [comment]
Ok, thank you.
Now that I read again all the paragraph in the wiki the description is ok.

**Pull request merged**
