### PR TITLE
New protos

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
- [x] Add a gaz canister proto
- [x] Change the flower pot protos to a smaller model

### CODE REVIEW

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Since for the physics of the canister we expose just a boolean, we should ensure the default mass being applied is appropriate. Is it the case already?
Other than that it looks good to me

**Comment by BenjaminDeleze** [comment]
> Since for the physics of the canister we expose just a boolean, we should ensure the default mass being applied is appropriate. Is it the case already? Other than that it looks good to me

Well spotted, 289 kg is maybe a bit too big.

**Comment by BenjaminDeleze** [comment]
I adjusted the size of the bottle slightly to better match a real bottle so that I could assign a correct mass to it.

**Review by ad-daniel — APPROVED** [review]
Thank you

**Pull request merged**
