### PR TITLE
Robotiq coupling link

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
Fix https://github.com/cyberbotics/webots/issues/6046#issuecomment-1731273838

Add the coupling link to the robotiq grippers.

It can be check with this world: [projects/robots/pal_robotics/tiago/worlds/tiago_robotiq_grippers.wbt](https://github.com/cyberbotics/webots/blob/master/projects/robots/pal_robotics/tiago/worlds/tiago_robotiq_grippers.wbt)

### CODE REVIEW

**Comment by omichel** [comment]
@thomaspeyrucain: please accept my invite to become a member of the Cyberbotics committers so that we can nominate you as a reviewer on this PR.

**Comment by thomaspeyrucain** [comment]
Hello @BenjaminDeleze,

I launched the simulation, looks good to me
image

**Review by thomaspeyrucain — APPROVED** [review]

**Comment by BenjaminDeleze** [comment]
> Hello @BenjaminDeleze,
> 
> I launched the simulation, looks good to me image

Thank you

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
