### PR TITLE
Merge master into develop

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
No conflicts.

### CODE REVIEW

**Review by omichel — APPROVED** [review]

**Review by omichel — CHANGES_REQUESTED** [review]
Well, it seems we need to fix some new cppcheck issues in the code of the develop branch.

**Comment by DavidMansolino** [comment]
It's actually not develop, but the other branch I merged just before merging the cppcheck on :disappointed:

**Comment by DavidMansolino** [comment]
I can't understand why `motor2()` and `motor3()` are raising the `Possible null pointer dereference` error but `motor()` is not :confused:

**Comment by omichel** [comment]
Maybe because in the base class (WbJoint.hpp) they return NULL and cppcheck is not smart enough to understand they are overridden?

**Comment by DavidMansolino** [comment]
That can be a good explanation indeed.

**Comment by omichel** [comment]
Anyhow, I believe it's not bad to cache the motor pointer to avoid calling the motor() method (which is not a simple getter) three times:
```C++
  WbMotor *m = motor();
  if (m && !m->isConfigureDone())
    m->setTargetPosition(position);
```
That should also fix the cppcheck errors.

**Comment by DavidMansolino** [comment]
> Anyhow, I believe it's not bad to cache the motor pointer to avoid calling the motor() method (which is not a simple getter) three times:
> 
> ```c++
>   WbMotor *m = motor();
>   if (m && !m->isConfigureDone())
>     m->setTargetPosition(position);
> ```
> 
> That should also fix the cppcheck errors for motor2 and motor3.

Yes, that's exactly what I am doing in #2340

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
