### PR TITLE
Fixed rendering of tracks and muscles in robot cameras (master)

### LINKED ISSUE #1808: pen_box test is failing on Windows
These two tests are failing on Windows with the following error message:
```
FAILURE with pen_box: The number of pixels painted after the first step should be lower than 20 not 1224.
```
```
FAILURE with pen_mesh_scaled: The number of pixels painted after the first step should be lower than 20 not 58
```

### PR DESCRIPTION
**Pull request by omichel**
Replaces #1834, targetting the master branch instead of develop.
Fixes #1808.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by omichel** [comment]
I believe I fixed the performance issue.
For my test world, the performance is now similar to the one of the master branch.

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
I am still having a small reproducible performance lost (from ~18x to 15-16x in my test scenario), but I can't explain it :-/
Can you reproduce this?

**Comment by omichel** [comment]
On my computer this is hardly perceptible... I can't explain it either as the overhead should now be very low.

**Pull request merged**
