### PR TITLE
Hotfix to use more contacts

### PR DESCRIPTION
**Pull request by brettle**
**Description**
API-compatible hotfix to issue where only the first 10 contact points are used and others are silently ignored.

**Related Issues**
This pull-request fixes issue #5768.

**Additional context**
A more complete fix which involves API changes is in PR #5769.

### CODE REVIEW

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]
Thank you!
There are just a couple of minor changes to be applied to the test.

Could you please also add an entry in the ChangeLog?
https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2023.md

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Comment by brettle** [comment]
Shall I merge or do you want to do that?

**Comment by stefaniapedrazzi** [comment]
You can merge it.

**Pull request merged**
