### PR TITLE
Hotfix webots-doc.css

### PR DESCRIPTION
**Pull request by fabienrohrer**
Minor adjustments to fix:

- [x] doc lists
- [x] doc navbar

Preview: https://www.cyberbotics.com/doc/reference/accelerometer?version=hotfix-webots-doc-css

### CODE REVIEW

**Comment by omichel** [comment]
That looks strange:
image

**Comment by fabienrohrer** [comment]
Yes, I know, this PR is not completed. I think just fixed it.

My last modifications are certainly correct, but the jsdelivr cache is not up-to-date (even if I purge them).

**Comment by fabienrohrer** [comment]
Let's wait to appreciate the results :-/

**Comment by fabienrohrer** [comment]
The jsdelivr cache is no up-to-date, and my 2 hot-fixes seems to work smoothly.

**Pull request merged**
