### PR TITLE
Fix ROS camera recognition topic

### LINKED ISSUE #2114: rostopic echo /......./...../recognition_objects doesnt work: no message
Hi. First I met the problem the same as [#1637](https://github.com/cyberbotics/webots/issues/1637) with webots 2020a, then I upgraded webots to 2020b.
This time when I try to echo /..../...../recognition_objects, the datatype/md5sum error's gone, but there's no message at all. Other topics works fine.
This is my screenshot, what i got by rostopic hz /..../...../recognition_objects.
no_recog_info

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Fix #2114

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
Sorry I'm still testing..
If I disabled the camera it doesn't seem to work.. but maybe I have some issues in my code.

**Comment by omichel** [comment]
Shall we fix the `complete_test`?

**Comment by stefaniapedrazzi** [comment]
Yes, it would be better to fix the `complete_test` and make sure that the implemented callbacks are really called.

**Comment by DavidMansolino** [comment]
Please open an issue about this.

**Pull request merged**
