### PR TITLE
Fix test suite

### PR DESCRIPTION
**Pull request by ad-daniel**
**Description**

Fixes https://github.com/cyberbotics/webots/issues/5503

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Just for note this change fixed some issues with test_suite a couple of months ago: see #5269.

**Comment by ad-daniel** [comment]
Well, in `test_suite_supervisor` all the failures are written without `:`, only in `test_suite.py` they appear to have the `:`, so counting the number of `FAILURE` without the extra space nor any `:` might do both things at once

**Comment by ad-daniel** [comment]
or at least, it seems to catch the issue reported today: https://github.com/cyberbotics/webots/actions/runs/3470087015/jobs/5798561716, not sure how to reproduce the one that was solved before

**Comment by ad-daniel** [comment]
do you recall by any chance what was the issue (or how to reproduce it)? The logs seem to have expired

**Comment by ad-daniel** [comment]
It seems that the change now captures a failure with [the blur test,](https://github.com/cyberbotics/webots/actions/runs/3472188783/jobs/5803242320#step:7:1223) since the message contains not `:`.
It doesn't happen every run but I suspect it was silently ignored beforehand

**Comment by stefaniapedrazzi** [comment]
> do you recall by any chance what was the issue (or how to reproduce it)? The logs seem to have expired

Yes, I'm retrieving all the information now.

**Comment by ad-daniel** [comment]
I have re-introduced the bug you mentioned and it was indeed caught in this PR (https://github.com/cyberbotics/webots/actions/runs/3478475736/jobs/5816408035#step:7:1427).

This PR can either be merged now (knowing it might result in occasional failures due https://github.com/cyberbotics/webots/issues/5515) or otherwise it can be merged later when the blur issue is solved (in doing so other failures might silently go unnoticed until then).

**Pull request merged**
