### PR TITLE
Add Tutorial 6 Wheel Dimensions

### PR DESCRIPTION
**Pull request by lagnx**
**Description**
The wheel size in tutorial 6 is not given explicitly, I add the appropriate size.

**Tasks**
Add the list of tasks of this PR.
  - [x] set the appropriate size of wheel.

**Documentation**
If this pull-request changes the doc, add the link to the related page, 
https://www.cyberbotics.com/doc/guide/tutorial-6-4-wheels-robot?version=lagnx:patch-1

### CODE REVIEW

**Comment by lagnx** [comment]
The content is complete, I didn't read it carefully, sorry.

**Comment by omichel** [comment]
Your PR should target the released branch. I just changed it, but then you deleted your branch, which closed the PR...
You can re-create it from [here](https://github.com/cyberbotics/webots/edit/released/docs/guide/tutorial-6-4-wheels-robot.md).

**Comment by omichel** [comment]
Note also that the radius of the wheel is 0.04, see https://github.com/cyberbotics/webots/blob/released/projects/samples/tutorials/worlds/4_wheels_robot.wbt#L94

**Comment by omichel** [comment]
I also sent you an invite via GitHub to become a member of the Committers group, so that you can create your own branches on the webots repository and merge your own PRs.

**Comment by lagnx** [comment]
> I also sent you an invite via GitHub to become a member of the Committers group, so that you can create your own branches on the webots repository and merge your own PRs.

I'm sorry I don't have enough time to do it. Thank you for your invitation.

**Comment by omichel** [comment]
> I'm sorry I don't have enough time to do it. Thank you for your invitation.

That's super easy and will take you about 2 minutes:
1. accept my invite.
2. click  [here](https://github.com/cyberbotics/webots/edit/released/docs/guide/tutorial-6-4-wheels-robot.md), apply your changes and press the green button to create a PR.

**Pull request closed without merging**
