### PR TITLE
Improved the bounding boxes of the nao to make them not collide

### PR DESCRIPTION
**Pull request by Jean-Eudes-le-retour**
**Description**
The bounding objects have been improved so that they do not collide anymore when the selfCollision is set to true.

~~:warning:  Only the realistic arms of the Nao have been updated~~

**Screenshots**

Old bounding objects:
Screenshot from 2022-12-02 16-28-01

New bounding objects:
Screenshot from 2022-12-02 16-26-35

### CODE REVIEW

**Review by omichel — CHANGES_REQUESTED** [review]
It seems that several motion files don't work any more with this modified robot model...

**Review by omichel — COMMENTED** [review]
Did you update the screenshot in the initial PR description?
Did you check that all the NAO motions are working fine with the new model?

**Comment by Jean-Eudes-le-retour** [comment]
> Did you update the screenshot in the initial PR description?

I forgot to do it, it's updated now.

> Did you check that all the NAO motions are working fine with the new model?

I opened the nao_demo world and all the commands work now.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
