### PR TITLE
Correct Youbot wheels

### PR DESCRIPTION
**Pull request by mael25**
**Description**
Correct contactProperties of Kuka's YouBot robot and improve the keyboard controller.

**Related Issues**
This pull-request fixes issue #3024.

**Tasks**
- [x] Correct contactProperties
- [x] Controller: Velocity control with keyboard
- [x] Add keyboard to Matlab controller (currently only demo)
- [x] Fix keys with Shift modifier (Matlab)
- [x] Correct turning direction
- [x] Prevent auto-colliding configurations from happening
- [x] Update YouBot doc (contactProperties, etc.)

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Review by stefaniapedrazzi — COMMENTED** [review]
Thank you!
I could not test the matlab controller but the code seems fine.

Just note that also the "tower_of_hanoi.wbt" is using the youBot robot and it would be good to update the ContactPropetries in this world as well, so that the same are used for all the distributed worlds containing the youBot.

**Comment by mael25** [comment]
> Thank you!
> I could not test the matlab controller but the code seems fine.
> 
> Just note that also the "tower_of_hanoi.wbt" is using the youBot robot and it would be good to update the ContactPropetries in this world as well, so that the same are used for all the distributed worlds containing the youBot.

Thank you for the review, I have now updated this world as well!

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Pull request merged**
