### PR TITLE
Fix `Brake`s added to the second axis of a `Hinge2Joint` being applied to the non-transformed axis.

### PR DESCRIPTION
**Pull request by brettle**
**Description**

Fixes bug where`Brake`s added to the second axis of a `Hinge2Joint` were being applied to the non-transformed axis.

**Tasks**
Add the list of tasks of this PR.
  - [X] Update the [changelog](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md)

**Additional context**

I'll upload a test world that demonstrates the issue.

### CODE REVIEW

**Comment by brettle** [comment]
[Hinge2Test.zip](https://github.com/user-attachments/files/16384359/Hinge2Test.zip) is a test world that demonstrates the issue. Each of the 2 spinning boxes is connected to it's own Hinge2Joint and both joints have the same configuration except that the second one has the first hinge rotated by 90 deg. As a result both of the spinning boxes *should* be spinning at the same speed throughout the test, but they do not. The second box accelerates/decelerates as though the brake's damping constant was not applied.

**Comment by brettle** [comment]
Converted to draft because although the fix solves the problem for the test case, it does not solve the problem if the first hinge rotates *after* the world loads.

**Comment by brettle** [comment]
My latest commit seems to address the problem when hinge rotates after loading the world.

**Comment by brettle** [comment]
Here's an updated [Hinge2Test.zip](https://github.com/user-attachments/files/16395877/Hinge2Test.zip) which tests the rotate-after-load case.

**Comment by omichel** [comment]
It would be nice, if possible, to integrate this test in the test suite which runs in the CI.

**Comment by brettle** [comment]
> It would be nice, if possible, to integrate this test in the test suite which runs in the CI.

Done.

**Review by omichel — APPROVED** [review]
Excellent! Thank you.

**Pull request merged**
