### PR TITLE
Update to Qt 5.14.2 on Linux

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Update Qt dependency to 5.14.2 on Linux.
The new Qt version fixes a bug with `showMinimized` (see #453).

Note that Windows is also using 5.14.2, so probably it would also be good to update the Qt dependency on macOS.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
The code is compiling fine after updating to Qt 5.14.2 (this version was already used on Windows).
But Webots is crashing on quit after running a world with HTML robot windows.

**Comment by omichel** [comment]
I confirm Webots is not crashing on Windows after running a simulation with a HTML robot window with Qt-5.14.2.

**Comment by stefaniapedrazzi** [comment]
:heavy_check_mark: travis_unit

It would be better to also test on mac if deleting the robot window QWebEnginePage is causing issues.

**Comment by DavidMansolino** [comment]
I will test this evening on the mac.

**Comment by stefaniapedrazzi** [comment]
@DavidMansolino thank you!

To test you can simply run the test suite or run for example the `custom_html_robot_window.wbt` simulation and then quit Webots.

**Comment by stefaniapedrazzi** [comment]
I target the develop branch because this is not a hotfix (everything already works correctly) and we will release soon R2020b.
But yes, if the path is set correctly on Webots start, it should not break the compatibility unless users uses the distributed Qt libraries for their controller/plugins.

**Pull request merged**
