### PR TITLE
Merge develop to master

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Conflicts (resolved using the files on the develop branch):
* .github/workflows/test_suite_linux.yml
* .github/workflows/test_suite_linux_develop.yml
* .github/workflows/test_suite_mac.yml
* .github/workflows/test_suite_mac_develop.yml
* scripts/packaging/sync_controller_lib.sh

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Test suite passed on Ubuntu 18.04.
This PR is now ready for review.

**Comment by stefaniapedrazzi** [comment]
Actually the urdf test failed:
```
FAILURE with robot_urdf_tiago: check_urdf command is missing
```

**Comment by lukicdarkoo** [comment]
> Actually the urdf test failed:
> 
> ```
> FAILURE with robot_urdf_tiago: check_urdf command is missing
> ```

Maybe some sync problem related to #3221

**Comment by ad-daniel** [comment]
Maybe not, it happens to me sometimes. Rerunning the job usually makes it disappear. Very odd behavior though

**Review by lukicdarkoo — APPROVED** [review]
Thank you, the conflict resolutions look good

**Pull request merged**
