### PR TITLE
FLU: convert objects/kitchen

### PR DESCRIPTION
**Pull request by flmichel**
- [x] (172) objects/kitchen/utensils/protos/Spoon.proto
- [x] (173) objects/kitchen/utensils/protos/Plate.proto
- [x] (174) objects/kitchen/utensils/protos/WoodenSpoon.proto
- [x] (175) objects/kitchen/utensils/protos/Wineglass.proto
- [x] (176) objects/kitchen/utensils/protos/Carafe.proto
- [x] (177) objects/kitchen/utensils/protos/Fork.proto
- [x] (178) objects/kitchen/utensils/protos/Knife.proto
- [x] (179) objects/kitchen/utensils/protos/Glass.proto
- [x] (180) objects/kitchen/utensils/protos/Cookware.proto
- [x] (181) objects/kitchen/utensils/protos/Lid.proto
- [x] (183) objects/kitchen/components/protos/Sink.proto
- [x] (184) objects/kitchen/components/protos/Worktop.proto
- [x] (185) objects/kitchen/components/protos/HotPlate.proto
- [x] (186) objects/kitchen/breakfast/protos/CerealBox.proto
- [x] (187) objects/kitchen/breakfast/protos/BiscuitBox.proto
- [x] (188) objects/kitchen/breakfast/protos/HoneyJar.proto
- [x] (189) objects/kitchen/breakfast/protos/JamJar.proto

### CODE REVIEW

**Comment by ad-daniel** [comment]
Make sure the PR targets `feature-enu-plan` branch instead of `master`

**Comment by ad-daniel** [comment]
Just for information, for `objects` the header of the PROTO is used to generate the documentation, for instance the comments are used to describe the fields. Therefore if those fields are changed, the documentation also needs to be regenerated. So far at least the changes you made in the header aren't necessary (it's the script's fault, unfortunately it seems to strip the comments from the header)

**Comment by ad-daniel** [comment]
I've corrected the orientation of the `HoneyJar` and `Plate` so that the texture is also FLU and consistent with the rest. I've converted `HotPlate` as it wasn't done. 

The `Fridge` and `Oven` are already in FLU (or another PR changed them already) which is way they aren't mentioned in this PR.

**Review by BenjaminDeleze — COMMENTED** [review]
I think that `BiscuitBox` is oriented toward the back.

The default translation of `HotPlate` is wrong

`Carafe` seems strange, but I think it is because of the transparence and that it is right at the end.

`Plate` is wrong when changing it radius/ height

**Comment by ad-daniel** [comment]
Fixed everything except the `Carafe`. When I add the un-altered PROTO (i.e `feature-enu-plan` version) to this same world I can see the same effect, so whatever is causing it already appears to be present in the `feature-enu-plan` branch. Whether it's a matter of the lighting I don't know, but I don't believe is related to this PR.

**Review by BenjaminDeleze — APPROVED** [review]
Thank you!

**Pull request merged**
