### PR TITLE
Remove robotis python library from package

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Follow-up #5297:
fix package creation expecting a python folder that has been removed in #5297.

### CODE REVIEW

**Comment by omichel** [comment]
Oops... 🤭

**Comment by stefaniapedrazzi** [comment]
The macOS build failed with this error:
```
 # linking librobotis-op2_window.dylib
ld: warning: directory not found for option '-L/Users/runner/work/webots/webots/projects/robots/robotis/darwin-op/libraries/libzip'
ld: warning: directory not found for option '-L/Users/runner/work/webots/webots/projects/robots/robotis/darwin-op/libraries/libssh'
# compiling entry_points.cpp (x86_64)
ld: library not found for -lnihzip
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [build/release/librobotis-op2_window.dylib] Error 1
make[3]: *** [robotis-op2_window.Makefile] Error 2
make[2]: *** [robotis/darwin-op/plugins/robot_windows.Makefile] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by omichel** [comment]
The Linux test suite tests took very long and were cancelled. I suppose this is GitHub CI problem rather than a problem with this PR which we should merge before tonight to fix the R2023a nightly builds.

**Comment by omichel** [comment]
I believe I found and fixed the test suite hang. The test suite is passing locally, so this PR should now be ready for review and hopefully merged before tonight.

**Review by ad-daniel — APPROVED** [review]
Works on my side as well, I'll merge it as soon as the tests finish.

**Comment by omichel** [comment]
Thank you.

**Pull request merged**
