### PR TITLE
Web: Move Robot documentation

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
# Tasks

- Move all the documentation of the protos to webots.cloud.
- I also took the opportunity to improve some of the protos
- I removed the iCub as it was : ugly, not up to date and not a proto
- Turn the Scout into a proto (was only a world) as the demo is nice.
- Rename Tiago++ in Tiagopp
- Remove old ros module for Ure

### Add the `.proto` to `webots.cloud`

- Add a yaml file in the project root (parent of `/protos`) with `publish: true`
- Add the proto to webots.cloud/proto
- Test it (fields in the 3d viewer and documentation)

### Additional instruction for robot:

- Copy the guide/robot_name.md file to projects/robots/.../robot_name/protos/docs/

- With the docs/guide/images/robots/robots_name:
  - Copy the folder to projects/robots/.../robot_name/protos/docs/images
  - Delete the icon, model, and thumbnail.png pictures
- In the .md file:
  - Remove the title and the first image
  - Change the path of images to remove the robots folder
  - Modify urls that refered to base nodes (robots, solid) or other documentation pages
  - Remove the file location section
- In the proto file: 
  - Change the `documentation url` in the .proto file (make it point toward `released` even if it is not valid yet)

# Status

- [x] Appearances
- [x] Robots
  - [x] projects/robots/a4/portal/protos/Portal.proto
  - [x] projects/robots/abb/irb/protos/Irb4600-40.proto
  - [x] projects/robots/adept/pioneer2/protos/Pioneer2.proto
  - [x] projects/robots/adept/pioneer3/protos/Pioneer3at.proto
  - [x] projects/robots/adept/pioneer3/protos/Pioneer3DistanceSensor.proto
  - [x] projects/robots/adept/pioneer3/protos/Pioneer3dx.proto
  - [x] projects/robots/adept/pioneer3/protos/Pioneer3Gripper.proto
  - [x] projects/robots/bitcraze/crazyflie/protos/Crazyflie.proto
  - [x] projects/robots/bluebotics/shrimp/protos/Shrimp.proto
  - [x] projects/robots/boston_dynamics/atlas/protos/Atlas.proto
  - [x] projects/robots/boston_dynamics/spot/protos/Spot.proto
  - [x] projects/robots/clearpath/moose/protos/Moose.proto
  - [x] projects/robots/clearpath/pr2/protos/Pr2.proto
  - [x] projects/robots/dji/mavic/protos/Mavic2Pro.proto
  - [x] projects/robots/epfl/biorob/protos/GhostDog.proto
  - [x] projects/robots/epfl/biorob/protos/Salamander.proto
  - [x] projects/robots/epfl/biorob/protos/Yamor.proto
  - [x] projects/robots/epfl/lis/protos/Blimp.proto
  - [x] projects/robots/epson/scara_t6/protos/ScaraT6.proto
  - [x] projects/robots/festo/robotino3/protos/Robotino3HokuyoMountingSupport.proto
  - [x] projects/robots/festo/robotino3/protos/Robotino3Platform.proto
  - [x] projects/robots/festo/robotino3/protos/Robotino3.proto
  - [x] projects/robots/festo/robotino3/protos/Robotino3SickMountingSupport.proto
  - [x] projects/robots/festo/robotino3/protos/Robotino3WebcamMountingSupport.proto
  - [x] projects/robots/festo/robotino3/protos/Robotino3Webcam.proto
  - [x] projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto
  - [x] projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
  - [x] projects/robots/franka_emika/panda/protos/PandaHand.proto
  - [x] projects/robots/franka_emika/panda/protos/Panda.proto
  - [x] projects/robots/fujitsu/hoap2/protos/Hoap2.proto
  - [x] projects/robots/gctronic/elisa/protos/Elisa3DistanceSensor.proto
  - [x] projects/robots/gctronic/elisa/protos/Elisa3.proto
  - [x] projects/robots/gctronic/e-puck/protos/E-puckDistanceSensor.proto
  - [x] projects/robots/gctronic/e-puck/protos/E-puckGroundSensors.proto
  - [x] projects/robots/gctronic/e-puck/protos/E-puck.proto
  - [x] projects/robots/gctronic/e-puck/protos/Pi-puck.proto
  - [x] projects/robots/husarion/rosbot/protos/Rosbot.proto
  - [x] projects/robots/irobot/create/protos/Create.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsAxle.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsBase.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsBrickAdapter.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCube.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithCrossSlots.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithRoundSlots.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieFemaleCube.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieMaleCube.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubiePyramid.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieTriangle.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsDistanceSensor.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsFinger.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsGrabber.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsLEDAppearance.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsLightSensor.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsMotor.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsPivot.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsPlasticAppearance.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsTwister.proto
  - [x] projects/robots/kinematics/tinkerbots/protos/TinkerbotsWheel.proto
  - [x] projects/robots/kondo/khr-2hv/protos/Khr2hv.proto
  - [x] projects/robots/kondo/khr-3hv/protos/Khr3hv.proto
  - [x] projects/robots/k-team/hemisson/protos/Hemisson.proto
  - [x] projects/robots/k-team/khepera1/protos/Khepera1.proto
  - [x] projects/robots/k-team/khepera2/protos/Khepera2.proto
  - [x] projects/robots/k-team/khepera3/protos/Khepera3_DistanceSensor.proto
  - [x] projects/robots/k-team/khepera3/protos/Khepera3_Gripper.proto
  - [x] projects/robots/k-team/khepera3/protos/Khepera3_GroundSensor.proto
  - [x] projects/robots/k-team/khepera3/protos/Khepera3.proto
  - [x] projects/robots/k-team/khepera3/protos/Khepera3_USSensor.proto
  - [x] projects/robots/k-team/khepera4/protos/Khepera4InfraredSensor.proto
  - [x] projects/robots/k-team/khepera4/protos/Khepera4.proto
  - [x] projects/robots/k-team/koala/protos/Koala.proto
  - [x] projects/robots/kuka/youbot/protos/KukaBox.proto
  - [x] projects/robots/kuka/youbot/protos/Youbot.proto
  - [x] projects/robots/lego/mindstorms/protos/MindstormsRover.proto
  - [x] projects/robots/micromagic/mantis/protos/Mantis.proto
  - [x] projects/robots/micromagic/scoute/protos/Scout.proto
  - [x] projects/robots/mir/mir100/protos/Mir100.proto
  - [x] projects/robots/mir/mir100/protos/Mir100UltrasonicSensor.proto
  - [x] projects/robots/mobsya/thymio/protos/Thymio2Ball.proto
  - [x] projects/robots/mobsya/thymio/protos/Thymio2Pen.proto
  - [x] projects/robots/mobsya/thymio/protos/Thymio2.proto
  - [x] projects/robots/nasa/protos/Sojourner.proto
  - [x] projects/robots/neuronics/ipr/protos/IprHd6m180.proto
  - [x] projects/robots/neuronics/ipr/protos/IprHd6m90.proto
  - [x] projects/robots/neuronics/ipr/protos/IprHd6ms180.proto
  - [x] projects/robots/neuronics/ipr/protos/IprHd6ms90.proto
  - [x] projects/robots/nex/protos/FireBird6.proto
  - [x] projects/robots/niryo/ned/protos/Ned.proto
  - [x] projects/robots/nvidia/jetbot/protos/JetBot.proto
  - [x] projects/robots/nvidia/jetbot/protos/JetBotRaspberryPiCamera.proto
  - [x] projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoBody.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftHey5.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
  - [x] projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightHey5.proto
  - [x] projects/robots/pal_robotics/tiago_iron/protos/TiagoIron.proto
  - [x] projects/robots/pal_robotics/tiagopp/protos/Tiagopp.proto
  - [x] projects/robots/pal_robotics/tiago_steel/protos/TiagoSteel.proto
  - [x] projects/robots/pal_robotics/tiago_titanium/protos/TiagoTitanium.proto
  - [x] projects/robots/parallax/boebot/protos/BoeBot.proto
  - [x] projects/robots/picaxe/microbot/protos/Microbot.proto
  - [x] projects/robots/rec/fabtino/protos/Fabtino.proto
  - [x] projects/robots/robotis/bioloid/protos/BioloidDog.proto
  - [x] projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto
  - [x] projects/robots/robotis/darwin-op/protos/Darwin-op.proto
  - [x] projects/robots/robotis/darwin-op/protos/RobotisJersey.proto
  - [x] projects/robots/robotis/darwin-op/protos/RobotisOp2Hinge2.proto
  - [x] projects/robots/robotis/darwin-op/protos/RobotisOp2.proto
  - [x] projects/robots/robotis/darwin-op/protos/RobotisOp3.proto
  - [x] projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
  - [x] projects/robots/robotnik/summit_xl_steel/protos/SummitXlSteel.proto
  - [x] projects/robots/saeon/protos/Altino.proto
  - [x] projects/robots/softbank/nao/protos/BallCandy.proto
  - [x] projects/robots/softbank/nao/protos/Cart.proto
  - [x] projects/robots/softbank/nao/protos/Distributor.proto
  - [x] projects/robots/softbank/nao/protos/KeyHole.proto
  - [x] projects/robots/softbank/nao/protos/KeyPot.proto
  - [x] projects/robots/softbank/nao/protos/Key.proto
  - [x] projects/robots/softbank/nao/protos/LollipopCandy.proto
  - [x] projects/robots/softbank/nao/protos/NaoChallengeRoom.proto
  - [x] projects/robots/softbank/nao/protos/NaoJersey.proto
  - [x] projects/robots/softbank/nao/protos/Nao.proto
  - [x] projects/robots/softbank/nao/protos/NaoRoom.proto
  - [x] projects/robots/softbank/nao/protos/Shelves.proto
  - [x] projects/robots/softbank/nao/protos/Tray.proto
  - [x] projects/robots/softbank/nao/protos/VisualArmature.proto
  - [x] projects/robots/sony/aibo/protos/AiboErs7.proto
  - [x] projects/robots/sony/qrio/protos/QRIO.proto
  - [x] projects/robots/sphero/bb8/protos/BB-8.proto
  - [x] projects/robots/surveyor/protos/SurveyorSrv1.proto
  - [x] projects/robots/unimation/puma/protos/Puma560.proto
  - [x] projects/robots/universal_robots/protos/UR10e.proto
  - [x] projects/robots/universal_robots/protos/UR3e.proto
  - [x] projects/robots/universal_robots/protos/UR5e.proto

### CODE REVIEW

**Comment by ad-daniel** [comment]
I suggest we split this PR as well since there's over 200 PROTO:
@omichel: appearances
@ygoumaz: from portal to khepera4
@ad-daniel: from Koala to UR5e

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Thank you, nothing major from my side

- The other IPR robots don't appear to link back to IprHd6m90's page
- In Tiagopp, it should be possible to insert TiagoGripper and TiagoLeftHey5 in `endEffectorRightSlot` but they don't show up
- In TiagoRightArm/TiagoLeftArm, I suspect it should be possible to insert the grippers but currently can't
- In TiagoBase + TiagoBody, it should be possible to insert stuff in the arm slots 
- Bioloid points to a non-english site, should probably link to http://en.robotis.com/ instead. Also the video is private
- RobotisOp2 mentions a variant modeled using hinge2, we should probably link to it
- UR3e links to Robotiq3fGripper but it fails loading

**Comment by ad-daniel** [comment]
Actually, the insertion issues might be fixed already in my PR, not sure

**Review by omichel — DISMISSED** [review]
The appearances looks all good to me.

**Comment by BenjaminDeleze** [comment]
> * The other IPR robots don't appear to link back to IprHd6m90's page
> * In Tiagopp, it should be possible to insert TiagoGripper and TiagoLeftHey5 in `endEffectorRightSlot` but they don't show up
> * In TiagoRightArm/TiagoLeftArm, I suspect it should be possible to insert the grippers but currently can't
> * In TiagoBase + TiagoBody, it should be possible to insert stuff in the arm slots

It is fixed (the database was just not up to date with the `.proto` files)



> * Bioloid points to a non-english site, should probably link to http://en.robotis.com/ instead. Also the video is private
> * RobotisOp2 mentions a variant modeled using hinge2, we should probably link to it

It is fixed



> * UR3e links to Robotiq3fGripper but it fails loading

Yes it is normal and it will also be the case for the newly added RobotisOp2Hinge2 link. The links are already written for `released` as it will eventually be the goal of this PR and it would be a pain to check every proto and md when merging this branch in develop, then in master, then in released.

If you want to see if the link is working, replace `released` by `doc-add-robots` in the url or by `develop` in the case of the `Robotiq3fGripper`

**Review by ygoumaz — CHANGES_REQUESTED** [review]
Two robots are sinking into the ground:
* Robotino3SickMountingSupport 
* Moose

In addition, I don't know if it a good idea to fix this in this PR, but the titles of the sample worlds are often missing the link to the actual file on Github. For example, it is correct in the Crazyflie and the ROSbot but not in the Moose.

**Comment by BenjaminDeleze** [comment]
> Two robots are sinking into the ground:
> 
> * Robotino3SickMountingSupport
> * Moose

I fixed it for the Moose. But I am not sure if it is a good idea to fix i for the `Robotino3SickMountingSupport`.
Let me explain: the `Robotino3SickMountingSupport` is a PROTO that is built only to be inserted in the `Robotino3` (in the `bottomSlot` to be exact. In consequence, it is designed to perfectly fit at this position when inserted, without additional translation/rotation.
If I modified the default translation of the `Robotino3SickMountingSupport` to be well displayed in the `PROTO` viewer, it will break this. Except if I also modified the position of the bottom slot of the `Robotino3` but it would not make a lot of sense.

So I don't see a perfect solution, but I am leaning towards the option of leaving things as they are.

Note: that is not the only PROTO with this problem: for example, the `doorKnob`, `doorLever`, `cabinetHandle`, ...

> In addition, I don't know if it a good idea to fix this in this PR, but the titles of the sample worlds are often missing the link to the actual file on Github. For example, it is correct in the Crazyflie and the ROSbot but not in the Moose.

I will do it, as it should not take too long

**Comment by BenjaminDeleze** [comment]
> I fixed it for the Moose. But I am not sure if it is a good idea to fix i for the `Robotino3SickMountingSupport`. Let me explain: the `Robotino3SickMountingSupport` is a PROTO that is built only to be inserted in the `Robotino3` (in the `bottomSlot` to be exact. In consequence, it is designed to perfectly fit at this position when inserted, without additional translation/rotation. If I modified the default translation of the `Robotino3SickMountingSupport` to be well displayed in the `PROTO` viewer, it will break this. Except if I also modified the position of the bottom slot of the `Robotino3` but it would not make a lot of sense.
> 
> So I don't see a perfect solution, but I am leaning towards the option of leaving things as they are.
> 
> Note: that is not the only PROTO with this problem: for example, the `doorKnob`, `doorLever`, `cabinetHandle`, ...
> 
> >

The solution we choose after discussion is:
- if the proto is a `slot` then ensure that the floor is under the `boundingSphere` (like we already do for `device`)
- if the proto is not a `slot`, we let it as is.

**Comment by BenjaminDeleze** [comment]
> n addition, I don't know if it a good idea to fix this in this PR, but the titles of the sample worlds are often missing the link to the actual file on Github. For example, it is correct in the Crazyflie and the ROSbot but not in the Moose.

This is now done.

**Review by ygoumaz — APPROVED** [review]
Nice! Thank you!

**Review by omichel — APPROVED** [review]

**Review by ad-daniel — APPROVED** [review]
Thank you

**Pull request merged**
