### PR TITLE
Fix values greater than maxRange for the RangeFinder

### PR DESCRIPTION
**Pull request by BenjaminHug8**
**Description**
Values greater than `maxRange` for the `RangeFinder` should return `inf` but currently return `maxRange` value.

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Well spotted!
I am wondering if the `isnan` tests are necessary in the `motion_blur.frag` file. Thanks to the fix in the `encode_depth.frag`, they shouldn't happen any more, isn't it?

**Comment by BenjaminHug8** [comment]
The w component is used to normalize the coordinates of the vertices, it cannot be = 0.

**Comment by omichel** [comment]
> The w component is used to normalize the coordinates of the vertices, it cannot be = 0.

In that case, we should remove the test and add a comment explaining why it cannot be 0.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
