### PR TITLE
Enhancement Background Node

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix second part of #483:
  - [ ] Add python script / context menu to generate specular and diffuse irradiance textures.
  - [x] Extend the background node to add two new fields(name might still change):
    - [x] `specularIrradianceMap`.
    - [x] `diffuseIrradianceMap`.
    - [x] `luminosity` SFFloat.
  - [ ] Update `TexturedBackground` PROTO to use new mechanism.
  - [x] Rename the `cubemap` field of the Background node into `skyColorMap`.
  - [x] Cleanup the WbCubmap class to remove all the backing and use instead directly the texture from the two new fields.
  - [ ] Test.
  - [ ] Doc.
  - [ ] Changelog.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
More about hdr format:
> The  RGBE (.hdr) format  uses  8  bit  for  each  RGB  component  and another 8 bit for a shared exponent and uses run-length encoding as compression algorithm. 

(https://www.cg.tuwien.ac.at/research/publications/2006/Holzer-06-HDR/Holzer-06-HDR-.pdf)

**Comment by DavidMansolino** [comment]
#### The texture separation starts to work fine:
physically_based_rendering
(different texture for skyColorMap and SpecularColorMap)

Definitely, the hardest part will be to do the conversion from the actual HDR textures to jpg color textures and small HDR specular and diffuse textures.

**Comment by DavidMansolino** [comment]
The failure of the camera is due to a totaly different rendering when a camera is attached to a display in a Docker environment.

Native:
0x00EF00


Docker:
0x00EF00

**Comment by fabienrohrer** [comment]
I have to restart this project from scratch, eventually by cherry picking interesting parts.

**Pull request closed without merging**
