### PR TITLE
Fix Camera lens distortion

### LINKED ISSUE #2295: Vertical effect in spherical camera image
A user asked for vertical effect in spherical image because currently only horizontal effect is applied:

horizontal_effect
vertical_effect

It seems correct to also expect a vertical spherical effect.
So we should maybe evaluate:
* if it is interesting to add a vertical effect
* if `spherical` is the best description for the image effect or if we could choose a better name (for example `equirectangular` or `cylindric` projection instead of `spherical` projection)

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix #2295 and #2934:
Camera lens distortion uses the Brown's distortion model, but there were bugs in the implementation and the center was not used for the radial and tagential components.
Additional, to apply lens distortion it is needed to apply an inverted Brown's distortion model.

Now, the distortion is correctly applied both in X and Y directions, as well as symmetrically on the right/left of the image. Here is the result using `Lens { center = [0.5, 0.5], radialCoefficients = [-0.5, 0], tangetialCoefficients = [0, 0]}`:

lens_distortion

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
[Brown distortion model](https://en.wikipedia.org/wiki/Distortion_(optics)), that is used in the lens distortion fragment shader, applies lens correction and not lens distortion
So I'm now trying to compare the results with other tools that perform lens distortion/correction to check if the results are matching or if we need to invert the formula.

**Comment by stefaniapedrazzi** [comment]
The issue with the used formula was already raised here: https://github.com/cyberbotics/webots-dev/issues/5478

I found two papers providing formulas to render lens distortion:
1) [Realistic Lens Distortion Rendering](https://www.researchgate.net/publication/326968643_Realistic_Lens_Distortion_Rendering)
2) [An Exact Formula for Calculating Inverse Radial Lens Distortions](https://www.researchgate.net/publication/303703794_An_Exact_Formula_for_Calculating_Inverse_Radial_Lens_Distortions)

Formula in 2) only considers the radial distortion and not the tangential but it also generates wrong pincushion distortion if K1 is greater than 0.4.
This is why I chose formula 1) for the lens distortion shader.

However, with any of the two formulas (that are approximations) it is not possible to use the exact same parameters to correct the lens distortion.
And I didn't find any implementation applying the lens distortion to compare the results.
The implementations I found are using the Brown distortion model as-is to apply lens distortion even if it is meant for distortion correction.

**Review by omichel — APPROVED** [review]
Very good, thank you.

**Comment by egordv** [comment]
Hello!
The lens distortion model now seems to be correct, at least in the feature-robocup-controllers branch. 
But the output image with radial distortion doesn't take into account pixels that are outside of camera's visible area and thus has a heavy artefacts around it's borders. Please check the image provided:
image

Left is an undistorted image, right is distorted.  
I'm using PROTO with camera fieldOfView=1.762 and radialCoefficients = [-0.26, -0.26]
If resulting distorted pixel coordinate is outside the visible area - it will have a colour of the closest pixel inside the visible area.
This leads to heavy artifacts around distorted image area as in right part of an image provided.
The partially visible robocup soccer ball in the corner of an image looks really strange and confusing our detection pipeline (check the left lower corner of an image).
What I'm expecting is the pixels outside visible area to be black, not repeating closest visible pixel's colour.
The image without this artifact should look like this: 
image

**Comment by omichel** [comment]
See also this post: https://hl.forum.robocup.org/t/modeling-wideangle-lenses-in-webots/495/3

**Pull request merged**
