### PR TITLE
Update installation-procedure.md

### PR DESCRIPTION
**Pull request by omichel**
Fixed installation procedure on Linux servers.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Just for the note, we can probably take inspiration from this list (github action for a Ubuntu-server container):
https://github.com/cyberbotics/webots/blob/develop/.github/workflows/test_suite.yml#L89

**Comment by omichel** [comment]
I am not sure we want to write such a list in the documentation and maintain it up-to-date...
Wouldn't it be better to refer to this test_suite.yml file instead or have this list of dependencies listed in a separate file and included by test_suite.xml?

**Comment by DavidMansolino** [comment]
I like the idea of having a list of dependencies listed in a separate file and included by test_suite.xml!

**Comment by omichel** [comment]
I believe we should add a couple of bash scripts in `webots/src/install_scripts` that will install the necessary Debian packages.
E.g.: `linux_server_development_installer.sh` which would in turn call `linux_server_runtime_installer.sh`.
The first one would be installing all the packages needed for a development environment while the second one would be installing only the packages needed at run-time by Webots.
Theses scripts should be used by our CI files (including `test_suite.yml`), so that they tested on a daily basis.
We should refer to them in the development Wiki and documentation instead of trying (and probably failing) to maintain a list of packages in the documentation.

**Comment by DavidMansolino** [comment]
@omichel I see you unassigned yourself from this issue/PR, would you like me to take it?

**Comment by omichel** [comment]
Yes, please, as I am not sure what's the best way to implement it.

**Comment by DavidMansolino** [comment]
Replaced by #2008

**Pull request closed without merging**
