### PR TITLE
Add namespace to Ros Nodehandle and remove redundant robot name prefixes from Ros service and topic names

### PR DESCRIPTION
**Pull request by CumaOzavci**
**Description**
In order to run multiple robots in the same simulation, we need to spawn separate ROS Controllers for each robot. But current implementation does not support this. Ros Nodehandle needs to have a namespace.

**Related Issues**
This pull-request fixes issue #4086

**Tasks**
  - [x] Add namespace to Ros Nodehandle
  - [x] Remove redundant robot name prefixes from Ros service and topic names

**Screenshots**
As shown below, every robot has its own controller_manager interface now:

Screenshot from 2022-01-05 15-22-49

**Additional context**
- `model_name` topic is under global namespace. Therefore, all robots publishes to same `model_name` topic
- `clock` topic is under global namespace. To prevent conflicts, `--clock` parameter must be set carefully for each robot.
- This works on our models but needs to be tested further...

### CODE REVIEW

**Comment by omichel** [comment]
The CI tests are failing because the code changes don't respect our coding style for C++. Please setup clang-format to fix the problem as described [here](https://github.com/cyberbotics/webots/wiki/CPP-Coding-Style/#tools).

**Comment by CumaOzavci** [comment]
@omichel i will fix them next week

**Comment by cosmicog** [comment]
Hello, I wanted to help Cuma about this PR since the format changes were a bit boring and he was already frustrated of converting our old world and proto files to ENU.

I also didn't want to mess with my own clang configurations assuming that, just one or few files were problematic. I downloaded the config file and started fixing formats of the failed files after every CI fail, with the `clang-format` command and started editing them on Github web. That's why there's too many commits before the last one fixing the rest of the files.

I was going to do more work because of being lazy to write this single line command:
```bash 
for FILE in *; do clang-format --style=file $FILE >> ../out/$FILE; done
```

I also rebased our fork and hopefully it is good to go now.

**Comment by omichel** [comment]
Thank you @cosmicog! I just sent you a GitHub invite to become a member of the Webots committers group. @lukicdarkoo should be able to review the PR soon.

**Comment by cosmicog** [comment]
I just re-arranged some empty spaces 🙃 But thanks for the invite. I accepted and hopefully I will have time to contribute more.

**Comment by lukicdarkoo** [comment]
@CumaOzavci Thank you for this contribution.

Before merging this, we should have another PR in the webots_ros repo to adapt the existing simulations. All tutorials from [here](http://wiki.ros.org/webots_ros/Tutorials/Sample%20Simulations) should work.

**Comment by CumaOzavci** [comment]
> @CumaOzavci Thank you for this contribution.
> 
> Before merging this, we should have another PR in the webots_ros repo to adapt the existing simulations. All tutorials from [here](http://wiki.ros.org/webots_ros/Tutorials/Sample%20Simulations) should work.
> 
> Also, since we are changing the API, we should target the `develop` branch.

@lukicdarkoo, then i am closing this PR and reopening at `develop` branch. In the same time, i will test/change webots_ros repo.

**Pull request closed without merging**
