### PR TITLE
Add Light Sensor to Sensors List

### PR DESCRIPTION
**Pull request by CoolSpy3**
**Description**
`LightSensor` was not included in the guide's generic sensor list. Now it is :D

**Tasks**
Add the list of tasks of this PR.
  - [x] Update the documentation

**Documentation**
https://cyberbotics.com/doc/guide/sensors?version=DeepBlueRobotics:add-lightsensor-to-sensors-doc

### CODE REVIEW

**Comment by omichel** [comment]
Thank you for this addition. However, I believe the icon doesn't look great, as it has too many details. Can't we find a simpler replacement for it?

**Comment by CoolSpy3** [comment]
I just copied this icon from the [reference docs](https://github.com/cyberbotics/webots/blob/master/docs/reference/images/light_sensor.png). I can try to find another though. Where do you usually source images for this project from?

**Comment by omichel** [comment]
> I just copied this icon from the [reference docs](https://github.com/cyberbotics/webots/blob/master/docs/reference/images/light_sensor.png). I can try to find another though. Where do you usually source images for this project from?

We draw it by ourselves or find an icon which is available under an open license.

**Comment by omichel** [comment]
For example something like this:
LightSensor

**Comment by CoolSpy3** [comment]
Alright, good to know for the future! I replaced it with the image you attached

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
