### PR TITLE
Fix apply skyColor to appearance on background updates

### LINKED ISSUE #5105: Changing Skycolor does not update appearance
**Describe the Bug**
When having a simple `Background` node (not a `TextureBackground`) and an object with a `PBRAppearance`, the object will have some reflections that correspond to the `skyColor` field of the `Background`. However, when changing this color, the reflections do not change until save + reload.

**Steps to Reproduce**
1. Create a new empty world.
2. Insert a `Background` node.
3. Insert a `Tiago++` robot. The `Tiago++` will have blue reflections (as the default `skyColor` is blue).
4. Change the `skyColor` to yellow.
5. See that the `Tiago++` still has blue reflections.
6. Save and reload: now the `Tiago++` has yellow reflections.

**Expected behavior**
The reflections of objects should immediately be updated.

**Additional context**
Already present in R2021b

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
Fix #5105

### CODE REVIEW

**Comment by ad-daniel** [comment]
Just FYI CadShapes also have instances of PBRAppearances, so if the background changes they too must change. In theory the connections do exist, but we should make sure they adapt on-the-fly as well

**Comment by BenjaminDeleze** [comment]
It should work fine, but I will check

**Comment by BenjaminDeleze** [comment]
> Just FYI, CadShapes also have instances of PBRAppearances, so if the background changes they too must change. In theory the connections do exist, but we should make sure they adapt on-the-fly as well

It works

**Comment by BenjaminDeleze** [comment]
The test that fails is `FAILURE with supervisor_import_robot_node: The robot node has not been imported correctly
` and is not related to this PR

**Review by ygoumaz — APPROVED** [review]
Works nicely, thank you.

**Pull request merged**
