### PR TITLE
Feature altimeter

### PR DESCRIPTION
**Pull request by omichel**
Replaces #3029.
Attempt to fix the https://github.com/sishamilton/webots/tree/feature-altimeter branch which got messed-up after trying to resolve the conflicts from the GitHub web interface...
We will sync the submodule with https://github.com/cyberbotics/webots_ros/pull/63 afterwards.

### CODE REVIEW

**Review by lukicdarkoo — APPROVED** [review]
Thank you

> We will sync the submodule with [cyberbotics/webots_ros#63](https://github.com/cyberbotics/webots_ros/pull/63) afterwards.

Does this mean we will sync the ROS module in another PR?

**Comment by omichel** [comment]
> Does this mean we will sync the ROS module in another PR?

Maybe that's not the best and we should sync the ROS module in this PR, but the ROS PR should be accepted by the reviewers before we merge this one.

**Review by lukicdarkoo — APPROVED** [review]
Thank you

**Comment by omichel** [comment]
Oops, it seems we are missing a change log entry for this... I will add it now.

**Pull request merged**
