### PR TITLE
Cleanup simplify splash screen code

### PR DESCRIPTION
**Pull request by omichel**
Small cleanup (to be merged after the release).

### CODE REVIEW

**Review by stefaniapedrazzi — APPROVED** [review]
It works fine.

Just a detail that I noticed when testing, the Webots window is shown quite immediately above the splash screen on Linux and thus the splash screen is not very visible.

**Comment by omichel** [comment]
> Just a detail that I noticed when testing, the Webots window is shown quite immediately above the splash screen on Linux and thus the splash screen is not very visible.

Yes I know, this was the case before this PR, and I believe we could fix it only on Windows, not on Linux / macOS.

**Comment by DavidMansolino** [comment]
> > Just a detail that I noticed when testing, the Webots window is shown quite immediately above the splash screen on Linux and thus the splash screen is not very visible.
> 
> Yes I know, this was the case before this PR, and I believe we could fix it only on Windows, not on Linux / macOS.

It disappears when the loading dialog appears right? This is not the desired behavior?

**Comment by stefaniapedrazzi** [comment]
> > > Just a detail that I noticed when testing, the Webots window is shown quite immediately above the splash screen on Linux and thus the splash screen is not very visible.
> > 
> > 
> > Yes I know, this was the case before this PR, and I believe we could fix it only on Windows, not on Linux / macOS.
> 
> It disappears when the loading dialog appears right? This is not the desired behavior?

The slash screen remains open but the Webots window is displayed on top of it.
So instead of seeing the splash screen, I see only the black Webots window.

Screenshot from 2020-09-02 13-46-10

**Comment by DavidMansolino** [comment]
Oh yes you right, I never saw this before, because when the window is in 'maximized' mode it works fine:
image

**Comment by omichel** [comment]
Note that this PR didn't change the behavior, it merely simplify the code.

It works better on Windows where the splash screen remains over the main Webots windows until the world is loaded.
It's not the case for Linux or mac OS, but I believe we failed at fixing it on these platforms.

**Pull request merged**
