### PR TITLE
Make the robot window appear by default for competitions

### PR DESCRIPTION
**Pull request by Jean-Eudes-le-retour**
**Description**
This PR make the robot window appear by default for competitions on webots.could "try" page to mimic the behaviour of robotbenchmark.net

### CODE REVIEW

**Comment by BenjaminDeleze** [comment]
I think it is a good idea however I am not convinced of the approach.

By checking the url we make it dependant to `webots.cloud`. Morehover, if someone want to embed a simulation on its website and as the same variable in its url it will also open the robot window.

I would prefer to have a documented API function in `webotsView.js` to do it.

**Comment by omichel** [comment]
Yes, having a documented API function would be less hacky and also better documented.

**Comment by Jean-Eudes-le-retour** [comment]
Ok, I'll look for a better way of doing it

**Comment by BenjaminDeleze** [comment]
If you add this function as an API one, this is were it should be documented: https://github.com/cyberbotics/webots/blob/master/docs/guide/web-streaming.md

**Comment by BenjaminDeleze** [comment]
Good question,

We could call it `openRobotWindow` or `displayRobotWindow` and maybe rename the `showRobotWindow` into `showRobotWindowButton` to be clearer

**Comment by Jean-Eudes-le-retour** [comment]
But then we would need to append "Button" all other existing attributes and I don't how much this would break existing code?

**Comment by Jean-Eudes-le-retour** [comment]
Maybe we could call it something like `robotWindowOnStartup`?

**Comment by BenjaminDeleze** [comment]
> But then wouldn't we need to append "Button" all other existing attributes? I don't how much this would break existing code

Indeed, if we can avoid that, it may be better.


Just thought about something. How will webots know which robot window to open with an attribute?
It is maybe better to have a function which take the name of the window as parameter no?

**Comment by Jean-Eudes-le-retour** [comment]
> Just thought about something. How will webots know which robot window to open with an attribute?
It is maybe better to have a function which take the name of the window as parameter no?

Good idea, I'll do that

**Comment by Jean-Eudes-le-retour** [comment]
> Just thought about something. How will webots know which robot window to open with an attribute?
It is maybe better to have a function which take the name of the window as parameter no?

I think I found a better solution: we can set an attribute that tells the toolbar to make the main window visible or not

**Comment by Jean-Eudes-le-retour** [comment]
This PR can be tested on: https://testing.webots.cloud/run?version=R2023a&url=https%3A%2F%2Fgithub.com%2Fcyberbotics%2Frobot-programming-competition%2Fblob%2Fmain%2Fworlds%2Frobot_programming.wbt&type=competition&context=try

**Review by BenjaminDeleze — APPROVED** [review]
Seems good, thank you

**Pull request merged**
