### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by omichel**
I am merging the develop branch into the master branch in preparation of the release.
I had to manually fix conflicts in the following files:
- docs/discord/development-2020.md
- docs/discord/documentation.md
- docs/discord/news.md
- docs/discord/technical-questions-2020.md
- docs/reference/camera.md
- docs/reference/changelog-r2020.md
- projects/robots/festo/robotino3/protos/Robotino3Wheel.proto
- scripts/proto_splitter/proto2multi.py
- src/controller/cpp/Robot.cpp
- src/controller/java/Makefile

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Review by stefaniapedrazzi — APPROVED** [review]

**Comment by lukicdarkoo** [comment]
`this is test` is still in README :) Should it be there?

**Comment by omichel** [comment]
No, that's a mistake. I will fix it.

**Comment by Hanan-abd** [comment]
Hello 
How to record the point cloud data from lidar and save it as ply file in python code? 
2021-05-07_23h33_14

**Pull request merged**
