### PR TITLE
Fixed extern controller startup

### LINKED ISSUE #2641: The external controller fails if started before Webots in Windows
**Describe the Bug**
If you haven't started Webots (probably the `\\.\pipe` folder is not created) the external controller fails.

**Steps to Reproduce**
2. 
  ```log
  C:\Users\lukic>set WEBOTS_HOME=C:\Users\lukic\AppData\Local\Programs\Webots
  C:\Users\lukic>set PATH=%WEBOTS_HOME%\lib\controller;%WEBOTS_HOME%\msys64\mingw64\bin;%WEBOTS_HOME%\msys64\mingw32\bin;%PATH%
  C:\Users\lukic>set PYTHONPATH=%WEBOTS_HOME%/lib/controller/python38
  C:\Users\lukic>python -c "from controller import Robot; r = Robot()"
  Cannot open pipe file: \\.\pipe\webots_6068_1192306500
  Cannot connect to Webots on pipe: \\.\pipe\webots_6068_1192306500
  ```

**Expected behavior**
The external controller should wait for Webots.

**System**
 - Operating System: Windows 10
 - Webots: R2021a and R2021a rev1 (nightly from 12/1/2021)

### PR DESCRIPTION
**Pull request by omichel**
Fixes #2641.

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
I am still getting the error:
```
$ export WEBOTS_HOME="/C/tools/msys64/home/lukic/webots"
$ export PATH=$WEBOTS_HOME/lib/controller:$WEBOTS_HOME/msys64/mingw64/bin:$PATH
$ export LD_LIBRARY_PATH=$WEBOTS_HOME/lib/controller
$ export PYTHONPATH=$WEBOTS_HOME/lib/controller/python38
$ python -c "from controller import Supervisor; Supervisor()"
Cannot open pipe file: \\.\pipe\webots_11632_1411508369
Cannot connect to Webots on pipe: \\.\pipe\webots_11632_141150836
```

**Comment by omichel** [comment]
> 
> 
> I am still getting the error:
> 
> ```
> $ export WEBOTS_HOME="/C/tools/msys64/home/lukic/webots"
> $ export PATH=$WEBOTS_HOME/lib/controller:$WEBOTS_HOME/msys64/mingw64/bin:$PATH
> $ export LD_LIBRARY_PATH=$WEBOTS_HOME/lib/controller
> $ export PYTHONPATH=$WEBOTS_HOME/lib/controller/python38
> $ python -c "from controller import Supervisor; Supervisor()"
> Cannot open pipe file: \\.\pipe\webots_11632_1411508369
> Cannot connect to Webots on pipe: \\.\pipe\webots_11632_141150836
> ```

Very strange. I cannot reproduce this. Note that WEBOTS_HOME should be specified in Windows format, e.g., `C:\tools\msys64\home\lukic\webots` and not MSYS format. Are you sure you have the latest version (git fetch, git pull) and recompiled the libController?

**Comment by omichel** [comment]
Here is my environment (MSYS2 console):
```bash
$ printenv WEBOTS_HOME
D:\msys64\home\Olivier\webots

$ printenv PATH
/D/Program Files/Python38:/D/Program Files/Python38/Scripts:/D/msys64/home/Olivier/webots/msys64/mingw64/bin:/mingw64/bin:/usr/bin:/c/WINDOWS/system32:/c/WINDOWS:/D/msys64/home/Olivier/webots/lib/controller

$ printenv PYTHONPATH
D:\msys64\home\Olivier\webots\lib\controller\python38

$python -c"from controller import Supervisor; Supervisor()"
Cannot open pipe file: \\.\pipe\webots_11632_1411508369
Cannot connect to Webots on pipe: \\.\pipe\webots_11632_1411508369
Cannot open \\.\pipe\webots_11632_1411508369. Retrying in 1 second.
Delete C:\Users\Olivier\AppData\Local\Temp/webots-12345 to clear this warning.
Cannot open pipe file: \\.\pipe\webots_11632_1411508369
Cannot connect to Webots on pipe: \\.\pipe\webots_11632_1411508369
Cannot open \\.\pipe\webots_11632_1411508369. Retrying in 2 seconds.
Delete C:\Users\Olivier\AppData\Local\Temp/webots-12345 to clear this warning.
Cannot open pipe file: \\.\pipe\webots_11632_1411508369
Cannot connect to Webots on pipe: \\.\pipe\webots_11632_1411508369
Cannot open \\.\pipe\webots_11632_1411508369. Retrying in 3 seconds.
Delete C:\Users\Olivier\AppData\Local\Temp/webots-12345 to clear this warning.
Cannot open pipe file: \\.\pipe\webots_11632_1411508369
Cannot connect to Webots on pipe: \\.\pipe\webots_11632_1411508369
Cannot open \\.\pipe\webots_11632_1411508369. Retrying in 4 seconds.
Delete C:\Users\Olivier\AppData\Local\Temp/webots-12345 to clear this warning.
Cannot open pipe file: \\.\pipe\webots_11632_1411508369
Cannot connect to Webots on pipe: \\.\pipe\webots_11632_1411508369
Cannot open \\.\pipe\webots_11632_1411508369. Retrying in 5 seconds.
Delete C:\Users\Olivier\AppData\Local\Temp/webots-12345 to clear this warning.
```

**Comment by lukicdarkoo** [comment]
It should not be related to the paths as the paths are only used to define the location of the dynamic libraries which work. In the beginning, it was working, but then I tried "corrupting" the temporary folder and at that time it stopped working.

I will test it tomorrow properly. Switching a development environment takes a lot of time

**Comment by omichel** [comment]
Did you have a chance to test it?

**Comment by lukicdarkoo** [comment]
No, sorry, I got stuck with #2811

**Review by lukicdarkoo — APPROVED** [review]
It seems to be working well now. Thank you!

Later, I will try the nightly build with ROS.

**Pull request merged**
