### PR TITLE
Attempt to enable source test on Windows Github Action

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
This is just a simple test.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
With this PR we will be able to remove the per commit Appveyor test (which is often problematic because failing on first commit) and keep only the nightly for now.

I have used the Chocolatey package manager for this workflow, for the workflow compiling Webots we will for sure need to use MSYS, but for this one, using Chocolatey has several advantages such as it is already available (no need to download and install) on Github action, and it supports installing specific version of packages (which is safer in CI to avoid that an update out of our control suddenly breaks the CI).

**Review by omichel — DISMISSED** [review]
Thank you.
We should now remove the corresponding appveyor test.

**Comment by omichel** [comment]
Shall we also remove `.appveyor.yml`, `test/sources/generate_diff.py` and `test/sources/parent_branch.sh`?

**Comment by DavidMansolino** [comment]
> Shall we also remove `.appveyor.yml`, `test/sources/generate_diff.py` and `test/sources/parent_branch.sh`?

Yes sure, well spotted!

**Comment by DavidMansolino** [comment]
> We should now remove the corresponding appveyor test.

I will remove them as soon as this PR is merged and then master is merged into develop.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
