### PR TITLE
Commercial to Open-source

### PR DESCRIPTION
**Pull request by lukicdarkoo**
I am not sure about the capitalization, but it seems fine:
https://english.stackexchange.com/questions/157178/capitals-or-not-for-open-source
https://en.wikipedia.org/wiki/Open-source_software

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Thank you!

**Comment by omichel** [comment]
The last expected check seems to be lasting for ever, preventing to merge the PR. Not sure what's wrong here.

**Comment by omichel** [comment]
Shall we remove this test from the required checks in the repository settings?
image

**Comment by lukicdarkoo** [comment]
@omichel It seems it is a bug in GitHub Actions:
https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157

**Review by omichel — APPROVED** [review]

**Pull request merged**
