### PR TITLE
Fix clang-format option

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Try to fix `AllowAllConstructorInitializersOnNextLine` errors (#1120).

### CODE REVIEW

**Comment by fabienrohrer** [comment]
If `AllowAllConstructorInitializersOnNextLine` is set (to `true` or `false`) in my environment, I have this warning in atom:

Capture d’écran 2019-11-27 à 08 50 41

It seems that I installed clang-format correctly:

```
➜  repos clang-format --version
clang-format version 9.0.0 (tags/google/stable/2019-05-14)
```

**Comment by DavidMansolino** [comment]
And what about when you launch the test manually from the test suite?

**Comment by fabienrohrer** [comment]
Good point, it is working:

```
python tests/sources/test_cppcheck.py 
...
----------------------------------------------------------------------
Ran 3 tests in 66.668s

OK
```

I just discover that atom runs an internal clang-format binary, apparently bounded to 8.0:

```
➜  webots git:(revision) /Users/fabien/.atom/packages/clang-format/node_modules/clang-format/bin/darwin_x64/clang-format --version
clang-format version 8.0.0 (trunk 338962) (llvm/trunk 338965)
```

I will check if I can change this. So it's not related with the current issue.

**Comment by fabienrohrer** [comment]
Ok, it's simply a matter to set the correct `clang-format` executable in the atom clang-format package preferences:

Capture d’écran 2019-11-27 à 09 06 51

I just added a note in the related wiki page: https://github.com/cyberbotics/webots/wiki/CPP-Coding-Style#cs300-cyberbotics-clang-format-style-compliance

**Comment by stefaniapedrazzi** [comment]
I also tested locally and setting `AllowAllConstructorInitializersOnNextLine: true` is causing issues on other files but the current settings are working correctly.
So I don't understand what was the issue but it seems to work correctly.

**Pull request closed without merging**
