### PR TITLE
Fix robot component rotation

### LINKED ISSUE #1191: Weird behaviour in webots.min.js
**Describe the Bug**
The `webots.min.js` window that allows you to view a robot in its documentation page has some bugs in the rotation axes (the linear one tested were working fine). In addition, the button to reset the view and axes breaks all the robot configuration.
TIAGo base : wheels
TIAGo Iron : wheels, head and neck
TIAGo Steel : wheels, head, neck and arm
TIAGo Titanium: wheels, head, neck, arm, fingers
TIAGo++ : wheels, head, neck, arms, fingers

**Steps to Reproduce**
_Reset problem_
1. Go to 'https://cyberbotics.com/doc/guide/tiagopp?version=develop'
2. Click on `reset button`

_Rotational axis problem_
1. Go to 'https://cyberbotics.com/doc/guide/tiagopp?version=develop'
2. Move any `RotationalMotor` to see anormal behaviour

**Expected behavior**
The robot should have the same behaviour as in his world example that can be found at `WEBOTS_HOME/projects/robots/pal_robotics/tiago++/protos/Tiago++.proto`

**Screenshots**
_Reset problem_
Before clicking the button
webots_min_js_reset_1

After clicking the button
webots_min_js_reset_2

_Axis problem_
webots_min_js_axis

**System**
 - Operating System: Linux Ubuntu 18.04.03 LTS
 - Graphics Card: GeForce GTX 1060 3GB/PCIe/SSE2

**Additional context**
I used the script provided to generate the files used for `webots.min.js`

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Fix #1191 Deal with more cases, visible in the Tiago and the TurtleBot, where there is a `Joint.endPoint[Solid].rotation` not set to origin.
- [x] Remove the useless `initialPosition` field in the meta.json files.

Preview: https://cyberbotics.com/doc/guide/tiagopp?version=fix-robot-component-rotation

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
It seems to work perfectly :tada: 

Can you please update with develop to take the robotino into account.

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
