### PR TITLE
Fix Robot Web Component

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Fix robot web component.

**Related Issues**
This pull-request attempts to fix issue #1606

https://www.cyberbotics.com/doc/guide/spot?version=fir-robot-web-component

**Task List**
  - [x] Handle the ball-joint case.
  - [x] Export joint anchor.
  - [x] Handle the joint anchor on the JS side.
  - [x] Fix motor highlight location
  - [x] Fix camera highlight location
  - [x] Re-export all the robot web component.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Remains to regenerate all the X3D and JSON files, but I would like a first review before (while the PR diff is still readable).

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
That's all good to me so far. Please go ahead with the export of the other web robot components and I will make a second review.

**Comment by DavidMansolino** [comment]
I checked all the previously problematic robots and all of them are now working perfectly (except the robotino3, but this is not related to this PR: #2026) :partying_face:

**Pull request merged**
