### PR TITLE
proto model for robotiq 2finger 85 gripper 

### PR DESCRIPTION
**Pull request by ipa-rwu**
**Description**
robotiq 2 finger 85 gripper

**Related Issues**
This pull-request fixes issue  #1350

**Tasks**
Add the list of tasks of this PR.
  - [ ] Task 1
  - [ ] Task 2

**Documentation**
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=ipa-rwu-patch-1

**Screenshots**
TODO

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Very nice model!
It seems that the problem you are facing is caused by some missing joint (at the location indicated by the red arrows):
Capture du 2020-02-11 17-21-12
Probably that the urdf2webots importer is not handling correctly closed loop. I will check this tomorrow morning.

**Comment by DavidMansolino** [comment]
@ipa-rwu, I have fixed the missing joint issue. Let me know if this solves your issue.
If it works, I would suggest improving your model for better performance and stability.
The next step would be to improve the bounding objects, instead of using the meshes directly it would be better to use sets of basic geometries (such as cylinder, boxes, etc.).

**Comment by ipa-rwu** [comment]
@DavidMansolino Thank you very much. I tried your model. The good things is that "gripper_finger1_joint" can move a half part of gripper. As you can see below:

Screenshot from 2020-02-12 09-39-00

But According to this gripper, "gripper_finger1_joint" should control both part. As you can see in rviz.
Screenshot from 2020-02-12 09-40-41

I found a example where "finger_joiont" should be "gripper_finger1_joint" in our case.
display

**Comment by DavidMansolino** [comment]
Unfortunately, in Webots a motor can control only on joint, can't you simply apply the same command on the `gripper_finger2_joint` motor?
Note also, that from the original URDF file it seems there are two distinct joints.

**Comment by ipa-rwu** [comment]
@DavidMansolino Good to know. I will try to rewrite the driver.

**Comment by ipa-rwu** [comment]
@DavidMansolino I check the urdf of this gripper, 
`
        <joint name="${prefix}gripper_finger1_joint" type="revolute">
            <parent link="${prefix}gripper_base_link"/>
            <child link="${prefix}gripper_finger1_knuckle_link"/>
            <axis xyz="0 0 1"/>
            <origin rpy="${pi} 0.0 0.0" xyz="0.05490451627 0.03060114443 0.0"/>
            <limit lower="0.0" upper="0.804" velocity="2.0" effort="1000"/>
        </joint>

        <joint name="${prefix}gripper_finger2_joint" type="revolute">
            <parent link="${prefix}gripper_base_link"/>
            <child link="${prefix}gripper_finger2_knuckle_link"/>
            <axis xyz="0 0 1"/>
            <origin rpy="0.0 0.0 0.0" xyz="0.05490451627 -0.03060114443 0.0"/>
            <limit lower="-3.14" upper="3.14" velocity="100.0" effort="1000"/>
            <mimic joint="${prefix}gripper_finger1_joint"/>
`
Is it possible do it in webots?

**Comment by DavidMansolino** [comment]
Well spotted, I didn't saw the 'mimic joint' part.
Unfortunately, this is not yet possible in Webots.
However, as a workaround, you can implement this in the interface controller between Webots and ROS.

**Comment by ipa-rwu** [comment]
@DavidMansolino I can move these two joints now. But I found it is different between the one in rviz and in webots. Do you have any ideas? 
Screenshot from 2020-02-13 09-11-10
Screenshot from 2020-02-13 09-11-38

**Comment by DavidMansolino** [comment]
This is probably due to the fact that not only `gripper_finger1_joint` and `gripper_finger2_joint` are linked, but they are also linked to `gripper_finger1_inner_knuckle_joint`, `gripper_finger2_inner_knuckle_joint`, `gripper_finger1_finger_tip_joint` and `gripper_finger2_finger_tip_joint`.

By the way, we added the feature of linking joints together to our roadmap (#1359).

**Comment by DavidMansolino** [comment]
Moved to https://github.com/cyberbotics/community-projects/pull/16

**Pull request closed without merging**
