### PR TITLE
Fix lidar point cloud visualisation issue

### PR DESCRIPTION
**Pull request by ad-daniel**
**Related Issues**
This pull-request addresses issue #2660

**Description**
After changing lidar out-of-range behavior in PR #2509, vertexes can have INF components, in which case they shouldn't be added to the mesh for rendering, as it wouldn't make much sense.

PS: As to why having a single vertex that contains an INF component in an otherwise valid cloud of points prevents all others from being drawn wasn't investigated in this PR. It's normal or should be addressed in a different issue? 

**Video**

https://user-images.githubusercontent.com/44834743/105106992-58c8c600-5ab7-11eb-813b-91c1baff1497.mp4

https://user-images.githubusercontent.com/44834743/105107008-5ebea700-5ab7-11eb-8c50-511c2afb3fbb.mp4

**Test**
Validated only on ubuntu 20.04.

### CODE REVIEW

**Comment by omichel** [comment]
Thank you for this new great contribution.
However, it seems that `cppcheck` is not happy with it, from the [CI tests](https://github.com/cyberbotics/webots/pull/2666/checks?check_run_id=1731562639):
```
src/webots/nodes/WbLidar.cpp:444:45: error: The address of local variable 'x' is accessed at non-zero index. [objectIndex]
        if (isinf(vertex[0]) || isinf(vertex[1]) || isinf(vertex[2]))
                                            ^
src/webots/nodes/WbLidar.cpp:443:31: note: Address of variable taken here.
        const float *vertex = &pointArray()[k * resolution + l].x;
                              ^
src/webots/nodes/WbLidar.cpp:444:45: note: The address of local variable 'x' is accessed at non-zero index.
        if (isinf(vertex[0]) || isinf(vertex[1]) || isinf(vertex[2]))
```

**Comment by ad-daniel** [comment]
yes, oddly enough cppcheck on linux didn't give any error, only macos does. In practice in this case the modification doesn't really bring much as in the very next line `wr_dynamic_mesh_add_vertex` assumes the data is contiguous anyway. Whatever the case, it shouldn't give an error now.

**Review by omichel — CHANGES_REQUESTED** [review]
Thank you.
Unfortunately, we don't have the same versions of ccpcheck on the different CI machines and the one of the mac may differ from the one on Linux.
Another acceptable way of fixing it would have been to add a special comment to disable the cppcheck warning, which you be OK as well.
Anyway, I believe we still need a line in the change log (as this PR somehow fixes a regression).

**Review by omichel — APPROVED** [review]
Thank you!

**Pull request merged**
