### PR TITLE
Fix package creation on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix the copy of openssl libraries for Ubuntu 18.04: with previous instructions libraries were not found.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
@stefaniapedrazzi What is this status of this PR? => Could we postpone it?

**Comment by stefaniapedrazzi** [comment]
Yes, I will posptpone it.
I have to check the status again.
When I stopped this PR the status was that packages created on Ubuntu 18.04 were not working on Ubuntu 16.04, i.e. `webots_distro.c` is in any case broken for Ubuntu 18.04.

**Comment by stefaniapedrazzi** [comment]
I checked again and there is no longer issues with `libssl` and `libcrypto` when creating packages on Ubuntu 18.04. But for running the created tarball (on Ubuntu 18.04 I don't think it will work on Ubuntu 16.04) the `libminizip` was missing.

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
