### PR TITLE
Merge master into develop

### PR DESCRIPTION
**Pull request by DavidMansolino**
Conflicts:
  - src/webots/core/WbHttpReply.cpp

This merge is required to let the nightlies work on develop with Qt 5.15.1 on Windows

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Thank you.

**Comment by DavidMansolino** [comment]
It seems somehow the compilation of the ros controller is broken: https://github.com/cyberbotics/webots/runs/1231542853#step:5:2514

But I don't see anything related to this in the diff of this PR, I will check, it is probably broken on master too.

**Comment by DavidMansolino** [comment]
It seems the problem is not on our side:
```
2020-10-09T13:33:40.5424330Z E: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 91.195.240.87 80]
2020-10-09T13:33:40.5428458Z E: The repository 'http://packages.ros.org/ros/ubuntu bionic InRelease' is not signed.
2020-10-09T13:33:40.6316078Z Reading package lists...
2020-10-09T13:33:40.8245683Z Building dependency tree...
2020-10-09T13:33:40.8262292Z Reading state information...
2020-10-09T13:33:40.9439250Z E: Unable to locate package ros-melodic-ros-base
2020-10-09T13:33:40.9440619Z E: Unable to locate package ros-melodic-sensor-msgs
2020-10-09T13:33:40.9441801Z E: Unable to locate package ros-melodic-tf
```

I will check if there is any workaround.

**Comment by DavidMansolino** [comment]
I allow myself to merge even if the ros test fails because it is not on our hand, this will be fixed by the ros team soon (see https://github.com/osrf/www.ros.org/issues/92#issuecomment-706203112).

**Pull request merged**
