### PR TITLE
Merge master into develop

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Conflicts:
- .github/workflows/tests_doc.yml
- .github/workflows/tests_sources.yml
- docs/discord/development-2020.md
- docs/discord/news.md
- docs/discord/technical-questions-2020.md

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
@cyberbotics/maintainers I'm not sure about the changes in these files:
* .github/workflows/tests_doc.yml
* .github/workflows/tests_sources.yml

I also double checked that my local environment is up-to-date.
But I don't understand why it is still merging old commits to the master branch already applied in #2438.

**Comment by omichel** [comment]
@lukicdarkoo should review these changes as he is the author of them.

**Comment by lukicdarkoo** [comment]
@stefaniapedrazzi  It looks good, CI files in the `master` branch are updated, so the ones from the `develop` branch should be overwritten.

**Review by omichel — APPROVED** [review]

**Comment by omichel** [comment]
I will merge this PR now as it will hopefully fix the nightly snap creation for R2021a.

**Pull request merged**
