### PR TITLE
Fix missmatching tag between text and image

### PR DESCRIPTION
**Pull request by ShuffleWire**
fix https://github.com/cyberbotics/webots/issues/3094

### CODE REVIEW

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]
Thank you!
Could you please also fix the link to the same figure at line 94?

**Review by stefaniapedrazzi — APPROVED** [review]

**Comment by stefaniapedrazzi** [comment]
Wrong test failures will be fixed in #3099.

**Comment by ShuffleWire** [comment]
Nice, thanks :)

**Comment by stefaniapedrazzi** [comment]
I changed the base branch, because due to the test failure this cannot be merged directly in the `released` branch.
You should now be able to merge the this PR.

**Pull request merged**
