### PR TITLE
Cleanup Lidar isRotating

### PR DESCRIPTION
**Pull request by mael25**
**Description**
Optimization proposed by @ShuffleWire in #3476.

Replaced ` bool isRotating()` and `Qstring mActualType` by `bool mIsActuallyRotating`, so that the bool is computed once and not at each step (as `Lidar` type changes are applied only after save & reload).

### CODE REVIEW

**Review by ad-daniel — APPROVED** [review]
For the variable name, is there a reason you changed the name to `mIsActuallyRotating` instead of calling it `mIsRotating` similarly to the previous function's name?

Also, I believe we're back to the old method, meaning that unless it's an hotfix we should target develop instead

**Review by ad-daniel — COMMENTED** [review]
For the variable name, is there a reason you changed the name to `mIsActuallyRotating` instead of calling it `mIsRotating` similarly to the previous function's name?

Also, I believe we're back to the old method, meaning that unless it's an hotfix we should target develop instead

**Comment by mael25** [comment]
> For the variable name, is there a reason you changed the name to `mIsActuallyRotating` instead of calling it `mIsRotating` similarly to the previous function's name?
> 
> Also, I believe we're back to the old method, meaning that unless it's an hotfix we should target develop instead

In `WbLidar.hpp`, all the members variables that correspond to a field of the `Lidar` but which are computed during initialization and not affected by the user's changes in the Scene Tree have the 'actual' prefix. This is the case for the `Lidar` `type`  field since #2983.

Yes, we can target `develop`.

**Comment by mael25** [comment]
Replaced by #3490. (base branch change doesn't work)

**Pull request closed without merging**
