### PR TITLE
Tiago base IndexedFaceSet to meshes

### PR DESCRIPTION
**Pull request by omichel**

### CODE REVIEW

**Review by BenjaminDeleze — DISMISSED** [review]
Thank you

**Comment by BenjaminDeleze** [comment]
`Tiago_base` is working well but it seems to have broken the other version of Tiagos

**Comment by omichel** [comment]
After merging #5071, the other versions of the Tiago robot are now loading and running properly.

**Review by BenjaminDeleze — APPROVED** [review]
Thank you

**Pull request merged**
