### PR TITLE
Publish Webots controller to independent repository

### PR DESCRIPTION
**Pull request by lukicdarkoo**
We need C/C++ libs to build the new `webots_ros2` interface:
https://github.com/cyberbotics/webots_ros2/pull/221

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
The Windows deployment has passed in bc537b1 and Linux/macOS in e4d846a. Deployment is limited now only during the nightly builds.

**Comment by omichel** [comment]
That looks very good.
However, I have a question: did you consider committing the source files instead of the binary files for the libController? Committing source files would be easier (it has to be done only once, not for all platforms) and the binaries should be easy to reconstruct from the source on the webots_ros2 side. Also committing binary files on GitHub looks a little bit odd...

**Comment by lukicdarkoo** [comment]
> That looks very good.
> However, I have a question: did you consider committing the source files instead of the binary files for the libController? Committing source files would be easier (it has to be done only once, not for all platforms) and the binaries should be easy to reconstruct from the source on the webots_ros2 side. Also committing binary files on GitHub looks a little bit odd...

I considered it, but I haven't done an in-depth evaluation. Since we are already compiling Webots here I thought that is simpler for the end-users to have dynamic libraries.

Should I reconsider it? If you don't foresee problems with compilation I can try deploying c/cpp files.

**Comment by omichel** [comment]
I don't forsee any problem with the compilation of the C and C++ libraries. But my question was just out of curiosity. To me both options are equally fine, and in any case, it will always be possible to change later on if needed.

**Review by omichel — APPROVED** [review]

**Comment by lukicdarkoo** [comment]
If we choose to distribute .c/.cpp files then I would rather configure the CI in the `webots-controller` repo. That way we keep the `webots-controller` repo self-contained and independent from the main repository.

**Pull request merged**
