### PR TITLE
Feature flu factory

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
**Description**
- [x] (102) objects/factory/fire_extinguisher/protos/FireExtinguisher.proto
- [x] (103) objects/factory/conveyors/protos/ConveyorPlatform.proto
- [x] (104) objects/factory/conveyors/protos/ConveyorBelt.proto
- [x] (105) objects/factory/pipes/protos/TJoint.proto
- [x] (106) objects/factory/pipes/protos/PipeSection.proto
- [x] (107) objects/factory/pipes/protos/LJoint.proto
- [x] (108) objects/factory/pallet/protos/WoodenPalletStack.proto
- [x] (109) objects/factory/pallet/protos/WoodenPallet.proto
- [x] (110) objects/factory/valves/protos/LargeValve.proto
- [x] (111) objects/factory/valves/protos/SmallValve.proto
- [x] (112) objects/factory/valves/protos/LeverValve.proto
- [x] (113) objects/factory/containers/protos/PlasticCrate.proto
- [x] (114) objects/factory/containers/protos/PlasticFruitBox.proto
- [x] (115) objects/factory/containers/protos/MetalStorageBox.proto
- [x] (116) objects/factory/containers/protos/CardboardBox.proto
- [x] (117) objects/factory/containers/protos/WoodenBox.proto
- [x] (118) objects/factory/tools/protos/Washer.proto (need PipeBoundingObject)
- [x] (119) objects/factory/tools/protos/Wrench.proto
- [x] (120) objects/factory/tools/protos/Bolt.proto
- [x] (121) objects/factory/tools/protos/PlatformCart.proto
- [x] (122) objects/factory/tools/protos/Screwdriver.proto
- [x] (123) objects/factory/tools/protos/CapScrew.proto
- [x] (124) objects/factory/tools/protos/EyeScrew.proto (need Tor bounding object)
- [x] (125) objects/factory/tools/protos/Nut.proto
- [x] (126) objects/factory/tools/protos/PaintBucket.proto
- [x] (127) objects/factory/tools/protos/ScrewHole.proto
- [x] (128) objects/factory/tools/protos/ElectricalPlug.proto (need Extrusion)
- [x] (129) objects/factory/tools/protos/Hammer.proto
- [x] (130) objects/factory/tools/protos/EmergencyButton.proto
- [x] (131) objects/factory/manhole/protos/SquareManhole.proto

Concerning the orientation, I followed the convention defined by the `CapScrew` in #3589 to make the `nut`, `bolt`, `washer` and `eyescrew`.

### CODE REVIEW

**Review by lukicdarkoo — CHANGES_REQUESTED** [review]
Looks good, but I have a few minor comments:
- ConveyorPlatform: The object is below the ground by default.
- Hammer/Screwdriver: Interesting choice, however, it is not super consistent with e.g. screws. I am not sure what is the best approach.
- ElectricalPlug: The `cablePath` field doesn't match the object's coordinate system

**Comment by BenjaminDeleze** [comment]
> * ConveyorPlatform: The object is below the ground by default.

It was already the case before, so I am not sure if we want to convert it.

> * Hammer/Screwdriver: Interesting choice, however, it is not super consistent with e.g. screws. I am not sure what is the best approach.

I am not sure either. I made it consistent with the `wrench` and I don't see a `screwdriver` standing on the tip, but it is right that it is not consistent with the screws and bolt. So I don't know.

**Comment by lukicdarkoo** [comment]
> > * ConveyorPlatform: The object is below the ground by default.
> 
> It was already the case before, so I am not sure if we want to convert it.

We should fix it

**Comment by BenjaminDeleze** [comment]
I think I fixed all screws and nuts.  There is just for the `screwhole.proto` that I have a doubt.
I also fixed the height of the `ConveyorPlatform`

**Review by lukicdarkoo — APPROVED** [review]
> There is just for the screwhole.proto that I have a doubt.

We missed considering that :/ I believe it is fine as you did.

Thank you!

**Pull request merged**
