### PR TITLE
Feature plastic box

### PR DESCRIPTION
**Pull request by omichel**
This PR adds a couple of objects needed for a specific project:

- PlasticBox
- MetalStorageBox

Documentation link: https://cyberbotics.com/doc/guide/object-factory#containers?version=feature-plastic-box

### CODE REVIEW

**Review by lukicdarkoo — CHANGES_REQUESTED** [review]
Everything looks good to me except bounding objects. For the metal box, the bounding objects do not cover the upper part of the box: 
Peek 2020-11-03 16-23

For the fruit box, I think it would be a good idea to add one more bounding object in the corners to better approximate the curvature.

I believe it is important to use accurate collisions because of pick-and-place operations.

**Comment by omichel** [comment]
I fixed the bounding objects:
box
box_1

**Review by lukicdarkoo — DISMISSED** [review]
Thanks!

**Comment by omichel** [comment]
Sorry, I believe I misunderstood your comment about the corners of the plastic fruit box. Here is an improved version:
box

**Review by lukicdarkoo — APPROVED** [review]
Now, the bounding objects are quite accurate :) Thanks

**Pull request merged**
