### PR TITLE
FLU: convert cabinet

### PR DESCRIPTION
**Pull request by flmichel**
- [x] (208) objects/cabinet/protos/CabinetDoor.proto
- [x] (209) objects/cabinet/protos/CabinetDrawer.proto
- [x] (210) objects/cabinet/protos/Cabinet.proto
- [x] (211) objects/cabinet/protos/CabinetHandle.proto

### CODE REVIEW

**Comment by ad-daniel** [comment]
Looks good, the only misbhevarior I found is with this configuration:

```
Cabinet {
  translation -1.48 0.15 -0.79
  rotation 0 1 0 1.5708
  name "cabinet(5)"
  outerThickness 0.02
  rowsHeights [
    0.21, 0.21, 0.22
  ]
  columnsWidths [
    0.34, 0.47, 0.47
  ]
  layout [
    "RightSidedDoor (2, 1, 1, 3, 1.5)"
    "LeftSidedDoor (3, 1, 1, 3, 1.5)"
    "RightSidedDoor (1, 1, 1, 3, 1.5)"
    "Shelf (1, 2, 1, 0)"
    "Shelf (1, 3, 1, 0)"
    "Shelf (1, 1, 0, 3)"
    "Shelf (2, 1, 0, 3)"
  ]
  handle CabinetHandle {
    translation 0.1 0 0
    handleLength 0.1
    handleRadius 0.008
    handleColor 0.427451 0.513725 0.533333
  }
  primaryAppearance PaintedWood {
    colorOverride 0.2 0.2 0.2
  }
  secondaryAppearance PaintedWood {
    colorOverride 0.2 0.2 0.2
  }
}
```
which resulted in this
c1

**Comment by ad-daniel** [comment]
Actually no, the error is in the world side when defining the `handle` node. Should we fix it right away or when we double check the worlds ?

**Comment by omichel** [comment]
> 
> 
> Actually no, the error is in the world side when defining the `handle` node. Should we fix it right away or when we double check the worlds ?

I would fix it right away. It's always better to fix errors when we spot them.

**Comment by ad-daniel** [comment]
The handles are wrong in virtually all the worlds. I'll fix it.

**Comment by ad-daniel** [comment]
The open side in the `CabinetDrawer` and the hinges were wrong. I've already fixed the translations of the handles in the world that specify them. There are two worlds in the `webots_ros` repository that require the same treatment but I suppose it can only be fixed when we merge this branch into develop?

Here's a custom world with several cabinets inside: [ref_cabinet.zip](https://github.com/cyberbotics/webots/files/7143905/ref_cabinet.zip)

**Review by BenjaminDeleze — APPROVED** [review]
Thank you!

**Pull request merged**
