### PR TITLE
Fixed performance issue

### LINKED ISSUE #2426: Performance issue
**Describe the Bug**
I notice a drop in performance since commit: https://github.com/cyberbotics/webots/commit/21dcb0dd8545cb7530a7f97933eceefb99f6819d

**Steps to Reproduce**
Here is a world for reproducing the issue: [test_simplified.zip](https://github.com/cyberbotics/webots/files/5476741/test_simplified.zip)

1. open the world with with Webots R2020b
2. start the simulation and check for the speed (11x on my computer)
3. open the same world with Webots build from commit 21dcb0dd8545cb7530a7f97933eceefb99f6819d
4. start the simulation and check for the speed (0.05x on my computer)

**Expected behavior**
The speed should be the same (or even faster :wink:)

**Screenshots**
Here is a screencast of my simulation using commit 21dcb0dd8545cb7530a7f97933eceefb99f6819d. With R2020b the simulation runs 0.28x even when the arm grab the hexagonal tile. In the video, the speed is twice slower and even more when the arm grab the tile.
https://youtu.be/59HirFdyYnU

**System**
Custom docker based on Ubuntu 18.04 with Webots built from sources

### PR DESCRIPTION
**Pull request by omichel**
Fix #2426.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Review by stefaniapedrazzi — COMMENTED** [review]
Thank you!
These simple changes are already a big improvement in the performance but the simulation is still running slower than in R2020b.

Here are the speedometer values i get when running the user world on my Linux 18.04 (all branches compiled in release mode) :
* Webots R2020b: 16x
* master branch:    0.02x
* this branch:          6.5x

Do you get the same?

**Comment by Acwok** [comment]
Thank you @omichel @stefaniapedrazzi !
I get the same speed between R2020b and this branch now (11x).

**Comment by omichel** [comment]
I am getting about the same speed as well (even slightly better on this branch), tested on Windows 10:
- R2020b: 13.3x
- this branch: 13.5x

**Comment by omichel** [comment]
@stefaniapedrazzi: are you sure you compiled this branch in `release` mode (including ode and wren)?

**Comment by stefaniapedrazzi** [comment]
Ok, yes I compiled everything in release mode.
but I will check again.

**Comment by stefaniapedrazzi** [comment]
by the way, isn't better to mention this fix in the ChangeLog given that it was affecting the last release version?

**Comment by stefaniapedrazzi** [comment]
I confirm I get slightly better performance as well.
Probably I had some other process running in background I didn't notice it.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you

**Pull request merged**
