### PR TITLE
Fix `sumo_interface_example.wbt`

### PR DESCRIPTION
**Pull request by ad-daniel**
**Description**
Attempt to fix https://github.com/cyberbotics/webots/issues/3281.
Ditto. It fixes the controller crash, but it remains to be seen if that was the cause for the Windows crash as well.

### CODE REVIEW

**Comment by omichel** [comment]
According to my tests, this doesn't fix the crash of Webots, unfortunately.

**Comment by ad-daniel** [comment]
Any clue as to what makes it crash? Is the stack available?

**Comment by omichel** [comment]
I cannot reproduce the crash anymore...

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
