### PR TITLE
Fix configuration of IntertialUnit after reset

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
The inertial unit is not correctly configured after reset (from the GUI) and makes controller crashing.

This is reproducible in the develop branch (but not in the master branch) by running and then resetting the `propeller.wbt` simulation.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
`robot_urdf_prob3` test failed but seems unrelated to this PR.

**Comment by stefaniapedrazzi** [comment]
I started again the tests and only the Windows test failed this time.

**Review by lukicdarkoo — APPROVED** [review]
Thank you!

It is strange it was working before

**Comment by stefaniapedrazzi** [comment]
> It is strange it was working before

It was working before because the coordinate system was not set in the configure message.
This has been changed recently in the develop branch.

**Pull request merged**
