### PR TITLE
Switch the service to retrieve the Webots version from Cyberbotics to GitHub

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix https://github.com/cyberbotics/webots/issues/1107
Use the GithHub release REST API: https://developer.github.com/v3/repos/releases (using raw or jsdelivr seems to be bad long term choices)

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
👀

**Comment by DavidMansolino** [comment]
Not related to this PR but I just figured out that it is strange to have the 'Check for Updates' in the 'Tools' menu on Windows, it will probably suit better in the 'Help' menu (more standard, and intuitively I was looking for it in this menu).

**Comment by fabienrohrer** [comment]
Very true, I'm opening a new PR with this modification right now..

**Pull request merged**
