### PR TITLE
Add macOS to GitHub Action Worflow

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Add macOS to the compilation and test workflow.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Test suite is not yet functional because of #2110, but this workflow is already testing compilation and installation (in two different stages), which is already useful.

Note that I started by adding macOS in the same file as the linux tests, but it was a mess, so I finally preferred to have a separate file for macOS, this implies some small duplications, but this is way more cleaner and will be way more simple to maintain.

**Review by omichel — APPROVED** [review]
Thank you.
Maybe we can check if the `LIBGL_ALWAYS_SOFTWARE` environment variable is really needed on macOS.

**Comment by DavidMansolino** [comment]
> Maybe we can check if the LIBGL_ALWAYS_SOFTWARE environment variable is really needed on macOS.

Good point, that looks indeed to be MESA specific: https://docs.mesa3d.org/envvars.html

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
