### PR TITLE
Fixed appveyor Python 3.9 build

### PR DESCRIPTION
**Pull request by omichel**
This was likely causing the problem with the nightly builds and Python 3.9.

### CODE REVIEW

**Comment by omichel** [comment]
It works: https://ci.appveyor.com/project/omichel/webots-master

**Comment by omichel** [comment]
(I believe there is no need to wait for the Linux and mac OS tests to complete)

**Comment by DavidMansolino** [comment]
> (I believe there is no need to wait for the Linux and mac OS tests to complete)

Why are these other tests running? I don't see the corresponding label?

**Review by DavidMansolino — APPROVED** [review]
Thank you

**Pull request merged**
