### PR TITLE
Fix smile of MyBot robot

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix smile of MyBot robot:
* `accelerometer.wbt`: cylinder orientation is wrong and smile is hidden inside the body
* `camera_recognition.wbt`: smile is displayed on the back of the robot
* fix the smile when using a textured IFS

### CODE REVIEW

**Comment by omichel** [comment]
Thank you. The one on the camera_recognition still looks wrong:
camera_recognition_2
camera_recognition
camera_recognition_1

**Comment by stefaniapedrazzi** [comment]
I restored the status before the ENU conversion.
But you are right, it is still wrong.
I will also fix all the other instances using this smile.

**Comment by omichel** [comment]
If simpler, you can also use the one of `accelerometer.wbt` which is fine.

**Comment by stefaniapedrazzi** [comment]
I adjusted the coordinates of the IFS and now the smile is completely visible.

**Review by omichel — APPROVED** [review]
Nice, thank you.

**Pull request merged**
