### PR TITLE
Fix crash when changing a world after the backward compatibility adapta…

### LINKED ISSUE #3946: Crash with the backward compatiblity with world R2021b open in Webots R2022a `feature-enu-plan`
**Describe the Bug**
If the following world created in `R2021b` is open with the `feature-enu-plan` branch (R2022a), Webots will crash 100% of the time.

**Steps to Reproduce**

1. Download this world [my_world_copy.zip](https://github.com/cyberbotics/webots/files/7581784/my_world_copy.zip)
2. Open it with the Webots `feature-enu-plan` branch (R2022a).
3. Try to open any other world or to create a new one.
4. Webots crashes.

**Additional context**
If the version of the world is changed from `R2021b` to `R2022a`, it will not crash anymore.

### PR DESCRIPTION
**Pull request by lukicdarkoo**
Fixes #3946

### CODE REVIEW

**Review by ad-daniel — DISMISSED** [review]
Looks good to me.

It's unrelated to this PR but it appears that the backwards compatibility mechanism fails for this word, the flipping of the geometry in the bounding objects of the wheels is wrong (one of them is deleted entirely and the other isn't flipped). Might be worth opening an issue/investigating since it's a very simple robot

bug

**Comment by lukicdarkoo** [comment]
I will fix it in this PR

**Comment by lukicdarkoo** [comment]
I changed it, but it still has some problems - not all USE references are updated. If you save/load the world it looks fine.

**Comment by ad-daniel** [comment]
a test appears to fail, is it because it isn't synched with the branch?

**Comment by lukicdarkoo** [comment]
Synced with the parent branched and created an issue #3963

**Comment by ad-daniel** [comment]
So do we need to revert the fix you attempted and just keep the fix for the crash or keep both?

**Comment by lukicdarkoo** [comment]
> So do we need to revert the fix you attempted and just keep the fix for the crash or keep both?

There is just the crash fix. I will resolve the backward compatibility robustness in another PR as it turned out it is more complex than expected.

**Review by ad-daniel — APPROVED** [review]
Ah my bad, I must have mixed things up.
Thank you!

**Pull request merged**
