### PR TITLE
Fix macOs extern controller doc

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
This issue was reported by a user: https://stackoverflow.com/questions/59840278/running-an-external-python-controller-from-console#comment105846278_59856562

### CODE REVIEW

**Comment by DavidMansolino** [comment]
@cyberbotics/development-team was the extern controller feature tested at least once in macOS by someone?

**Comment by DavidMansolino** [comment]
Even after with this fix the user reports a crash: https://stackoverflow.com/questions/59840278/running-an-external-python-controller-from-console

**Comment by fabienrohrer** [comment]
:eyes:

**Comment by fabienrohrer** [comment]
(I tested this feature in the last QA)

**Comment by fabienrohrer** [comment]
I confirm that setting the environment variables as described in the doc allow to run the Python controller smoothly:

```
$ export WEBOTS_HOME=/Applications/Webots.app
$ export DYLD_LIBRARY_PATH=$WEBOTS_HOME/lib/controller
$ export PYTHONPATH=/Applications/Webots.app/lib/controller/python37
```

Capture d’écran 2020-01-22 à 15 28 41

The crash that the user experiments may come from a Python mismatch, typically when installed from Brew. I'm answering him on StackOverflow.

**Pull request merged**
