### PR TITLE
Drop Python 2

### PR DESCRIPTION
**Pull request by fabienrohrer**
Implement #1096

### CODE REVIEW

**Comment by fabienrohrer** [comment]
We should also certainly upgrade to Python 3.8 on every OS, but I prefer to do this in another PR, once this one is merged.

**Comment by stefaniapedrazzi** [comment]
> We should also certainly upgrade to Python 3.8 on every OS, but I prefer to do this in another PR, once this one is merged.

Note that the default Python version on Ubuntu 18.04 is 3.6.
This is the one we should make sure that is supported on Linux.

**Comment by stefaniapedrazzi** [comment]
Default Python version on Ubuntu 16.04 is 2.7, I'm not sure it is good to completely drop the support of python2 if we still support Ubuntu 16.04.

**Comment by fabienrohrer** [comment]
The aim of this PR is also to evaluate the feasibility of this drop. I'm also still not sure this is a good idea.

We could discuss of this on our next meeting.

But for sure, I really would like to go forward with this topic. Ubuntu 16.04 could install Python 3.5 easily, and following our release logics, we will drop 16.04 support in 5 months, when 20.04 LTS will be released.

**Comment by stefaniapedrazzi** [comment]
Yes, I just wanted to point out some issues that this change could cause.
I think it is good to discuss it on Monday.

> But for sure, I really would like to go forward with this topic. Ubuntu 16.04 could install Python 3.5 easily, and following our release logics, we will drop 16.04 support in 5 months, when 20.04 LTS will be released.

Of course at some point users won't never use Python 2.7. But personally I think that it is too early to do it in R2020a.
Changing the documentation is ok, but at least I would keep the precompiled libcontroller so that it can still work out-of-the box

**Comment by fabienrohrer** [comment]
You're probably right, but it's annoying, because the maintenance complexity will remain for months. Anyway, I'm stopping there, and we could decide what to do on Monday. I will try to create a pros/cons list.

**Comment by fabienrohrer** [comment]
It's not the time to drop Python 2 yet.

**Pull request closed without merging**
