### PR TITLE
Enhancement viewpoint standard views

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Addresses  #4111:
* [x] Rename Viewpoint standard views
* [x] Add actions to move to default standard view related to the selected object
* [x] Improve keyboard shortcuts
* [x] Add ChangeLog entries
* [x] Update documentation

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
It remains to update the `context_menu.png` documentation image from Windows, but otherwise this PR is ready for review.

**Comment by stefaniapedrazzi** [comment]
Finally, I completely replaced the screenshot with an updated one taken on Linux.

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Overall seems to work well, the only thing I find a bit odd is that when aligning to a face, no "rectification" takes place, what I mean is:

1. Open `skin_animated_humans.wbt`
2. Select robert and `ALT + SHIFT + 2`
3. The view is indeed correct and facing Robert, but it's slanted rather than actually face-on

To make it more evident you can reload, move the camera such that you're looking at Robert from above, and then press `ALT + SHIFT + 2`. Again it's not "wrong" but the slant is quite big

If you reload and do `ALT + 2`, the movement of the camera seems to be a combination of three steps and the last of the 3 takes care of re-aligning with the axes. Is it possible that the object-focused orbits are missing the last step?

**Comment by stefaniapedrazzi** [comment]
I will check because I probably introduce it when cleaning up the code.

**Comment by stefaniapedrazzi** [comment]
It should be fixed now.

**Comment by ad-daniel** [comment]
Perfect!
I might however have found an edge case. It doesn't always happen, so not sure exactly what triggers it, either way I have it often when I:
- load same world: `SHIFT + ALT + 2`
- when done `SHIFT + ALT + 3`
- when done `SHIFT + ALT + 3` yet again.

Although you're already facing from the back, it still triggers an animation and gets back to the same spot. Not the end of the world but doesn't seem to happen in the other cases. It seems like you NEED to move from FRONT to BACK for it to happen, if you get to the BACK from any other direction it doesn't.

**Comment by stefaniapedrazzi** [comment]
I improved the comparison of quaternions and it should solve the problem with the orbit to the same view.
I can no longer reproduce it.

**Comment by ad-daniel** [comment]
Still happens to me unfortunately

**Comment by stefaniapedrazzi** [comment]
Yes, I will commit very a soon a fix.
But I found another orbit behavior exception that I'm fixing too.

**Comment by ad-daniel** [comment]
I don't know if you're still investigating, but I just wanted to say that the last commit solved all issues for me

**Comment by stefaniapedrazzi** [comment]
Perfect!
There is still a weird orbit when moving from back to left view of the human.
It seems a singularity somewhere but I didn't find it yet.

**Comment by stefaniapedrazzi** [comment]
I'm still testing different worlds, but it now seems to work properly.

**Review by ad-daniel — APPROVED** [review]
Works very well for me too, thank you!

**Pull request merged**
