### PR TITLE
Add objects to webots.cloud

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
**Description**
As those protos have no dedicated documentation, this PR will mainly consist in yaml files and changing the documentation url of the .proto

- [x] projects/objects/advertising_board/protos/AdvertisingBoard.proto
- [x] projects/objects/animals/protos/Cat.proto
- [x] projects/objects/animals/protos/Cow.proto
- [x] projects/objects/animals/protos/Deer.proto
- [x] projects/objects/animals/protos/Dog.proto
- [x] projects/objects/animals/protos/Fox.proto
- [x] projects/objects/animals/protos/Horse.proto
- [x] projects/objects/animals/protos/Rabbit.proto
- [x] projects/objects/animals/protos/Sheep.proto
- [x] projects/objects/apartment_structure/protos/Ceiling.proto
- [x] projects/objects/apartment_structure/protos/DoorKnob.proto
- [x] projects/objects/apartment_structure/protos/DoorLever.proto
- [x] projects/objects/apartment_structure/protos/Door.proto
- [x] projects/objects/apartment_structure/protos/GenericDoorAppearance.proto
- [x] projects/objects/apartment_structure/protos/Radiator.proto
- [x] projects/objects/apartment_structure/protos/WallPlug.proto
- [x] projects/objects/apartment_structure/protos/Wall.proto
- [x] projects/objects/apartment_structure/protos/Window.proto
- [x] projects/objects/balls/protos/Ball.proto
- [x] projects/objects/balls/protos/FifaSoccerBall.proto
- [x] projects/objects/balls/protos/PingPongBall.proto
- [x] projects/objects/balls/protos/RobocupSoccerBall.proto
- [x] projects/objects/balls/protos/SoccerBall.proto
- [x] projects/objects/bathroom/protos/BathroomSink.proto
- [x] projects/objects/bathroom/protos/Bathtube.proto
- [x] projects/objects/bathroom/protos/Toilet.proto
- [x] projects/objects/bathroom/protos/WashingMachine.proto
- [x] projects/objects/bedroom/protos/Bed.proto
- [x] projects/objects/bedroom/protos/PhotoFrame.proto
- [x] projects/objects/buildings/protos/Auditorium.proto
- [x] projects/objects/buildings/protos/Barn.proto
- [x] projects/objects/buildings/protos/BigGlassTower.proto
- [x] projects/objects/buildings/protos/Building.proto
- [x] projects/objects/buildings/protos/BuildingUnderConstruction.proto
- [x] projects/objects/buildings/protos/BungalowStyleHouse.proto
- [x] projects/objects/buildings/protos/Carwash.proto
- [x] projects/objects/buildings/protos/Church.proto
- [x] projects/objects/buildings/protos/CommercialBuilding.proto
- [x] projects/objects/buildings/protos/ComposedHouse.proto
- [x] projects/objects/buildings/protos/CyberboticsTower.proto
- [x] projects/objects/buildings/protos/FastFoodRestaurant.proto
- [x] projects/objects/buildings/protos/GasStation.proto
- [x] projects/objects/buildings/protos/HollowBuilding.proto
- [x] projects/objects/buildings/protos/Hotel.proto
- [x] projects/objects/buildings/protos/HouseWithGarage.proto
- [x] projects/objects/buildings/protos/LargeResidentialTower.proto
- [x] projects/objects/buildings/protos/ModernHouse.proto
- [x] projects/objects/buildings/protos/ModernSuburbanHouse.proto
- [x] projects/objects/buildings/protos/MotelReception.proto
- [x] projects/objects/buildings/protos/Museum.proto
- [x] projects/objects/buildings/protos/OldResidentialBuilding.proto
- [x] projects/objects/buildings/protos/RandomBuilding.proto
- [x] projects/objects/buildings/protos/ResidentialBuilding.proto
- [x] projects/objects/buildings/protos/ResidentialBuildingWithRoundFront.proto
- [x] projects/objects/buildings/protos/ResidentialTower.proto
- [x] projects/objects/buildings/protos/SimpleBuilding.proto
- [x] projects/objects/buildings/protos/SimpleTwoFloorsHouse.proto
- [x] projects/objects/buildings/protos/SmallManor.proto
- [x] projects/objects/buildings/protos/SmallResidentialBuilding.proto
- [x] projects/objects/buildings/protos/SmallResidentialTower.proto
- [x] projects/objects/buildings/protos/StripBuilding.proto
- [x] projects/objects/buildings/protos/SuburbanHouse.proto
- [x] projects/objects/buildings/protos/TheThreeTowers.proto
- [x] projects/objects/buildings/protos/UBuilding.proto
- [x] projects/objects/buildings/protos/Warehouse.proto
- [x] projects/objects/buildings/protos/Windmill.proto
- [x] projects/objects/cabinet/protos/CabinetHandle.proto
- [x] projects/objects/cabinet/protos/Cabinet.proto
- [x] projects/objects/chairs/protos/Chair.proto
- [x] projects/objects/chairs/protos/OfficeChair.proto
- [x] projects/objects/chairs/protos/SimpleChair.proto
- [x] projects/objects/chairs/protos/WoodenChair.proto
- [x] projects/objects/computers/protos/ComputerMouse.proto
- [x] projects/objects/computers/protos/DesktopComputer.proto
- [x] projects/objects/computers/protos/Keyboard.proto
- [x] projects/objects/computers/protos/Laptop.proto
- [x] projects/objects/computers/protos/Monitor.proto
- [x] projects/objects/create_wall/protos/CreateWall.proto
- [x] projects/objects/drinks/protos/BeerBottle.proto
- [x] projects/objects/drinks/protos/Can.proto
- [x] projects/objects/drinks/protos/WaterBottle.proto
- [x] projects/objects/factory/containers/protos/CardboardBox.proto
- [x] projects/objects/factory/containers/protos/MetalStorageBox.proto
- [x] projects/objects/factory/containers/protos/PlasticCrate.proto
- [x] projects/objects/factory/containers/protos/PlasticFruitBox.proto
- [x] projects/objects/factory/containers/protos/WoodenBox.proto
- [x] projects/objects/factory/conveyors/protos/ConveyorBelt.proto
- [x] projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
- [x] projects/objects/factory/fire_extinguisher/protos/FireExtinguisher.proto
- [x] projects/objects/factory/forklift/protos/Forklift.proto
- [x] projects/objects/factory/gas_canister/protos/GasCanister.proto
- [x] projects/objects/factory/manhole/protos/SquareManhole.proto
- [x] projects/objects/factory/pallet/protos/WoodenPallet.proto
- [x] projects/objects/factory/pallet/protos/WoodenPalletStack.proto
- [x] projects/objects/factory/pipes/protos/LJoint.proto
- [x] projects/objects/factory/pipes/protos/PipeSection.proto
- [x] projects/objects/factory/pipes/protos/TJoint.proto
- [x] projects/objects/factory/tools/protos/Bolt.proto
- [x] projects/objects/factory/tools/protos/CapScrew.proto
- [x] projects/objects/factory/tools/protos/ElectricalPlug.proto
- [x] projects/objects/factory/tools/protos/EmergencyButton.proto
- [x] projects/objects/factory/tools/protos/EyeScrew.proto
- [x] projects/objects/factory/tools/protos/Hammer.proto
- [x] projects/objects/factory/tools/protos/Nut.proto
- [x] projects/objects/factory/tools/protos/PaintBucket.proto
- [x] projects/objects/factory/tools/protos/PlatformCart.proto
- [x] projects/objects/factory/tools/protos/Screwdriver.proto
- [x] projects/objects/factory/tools/protos/ScrewHole.proto
- [x] projects/objects/factory/tools/protos/Washer.proto
- [x] projects/objects/factory/tools/protos/Wrench.proto
- [x] projects/objects/factory/valves/protos/LargeValve.proto
- [x] projects/objects/factory/valves/protos/LeverValve.proto
- [x] projects/objects/factory/valves/protos/SmallValve.proto
- [x] projects/objects/floors/protos/CircleArena.proto
- [x] projects/objects/floors/protos/Floor.proto
- [x] projects/objects/floors/protos/RectangleArena.proto
- [x] projects/objects/floors/protos/UnevenTerrain.proto
- [x] projects/objects/freight/protos/IntermodalContainer.proto
- [x] projects/objects/freight/protos/IntermodalOfficeContainer.proto
- [x] projects/objects/fruits/protos/Apple.proto
- [x] projects/objects/fruits/protos/FruitBowl.proto
- [x] projects/objects/fruits/protos/Orange.proto
- [x] projects/objects/garden/protos/Barbecue.proto
- [x] projects/objects/garden/protos/DogHouse.proto
- [x] projects/objects/garden/protos/Gnome.proto
- [x] projects/objects/garden/protos/Pergolas.proto
- [x] projects/objects/garden/protos/PicketFence.proto
- [x] projects/objects/garden/protos/PicketFenceWithDoor.proto
- [x] projects/objects/garden/protos/Slide.proto
- [x] projects/objects/garden/protos/SwingCouch.proto
- [x] projects/objects/garden/protos/Swing.proto
- [x] projects/objects/garden/protos/TableWithUmbrella.proto
- [x] projects/objects/garden/protos/WateringCan.proto
- [x] projects/objects/garden/protos/Wheelbarrow.proto
- [x] projects/objects/gear/protos/Gear.proto
- [x] projects/objects/hospital/protos/Curtain.proto
- [x] projects/objects/hospital/protos/DripStand.proto
- [x] projects/objects/hospital/protos/EmergencyExitSign.proto
- [x] projects/objects/hospital/protos/HandSanitizer.proto
- [x] projects/objects/hospital/protos/HospitalBed.proto
- [x] projects/objects/hospital/protos/MedicineBottle.proto
- [x] projects/objects/kitchen/breakfast/protos/BiscuitBox.proto
- [x] projects/objects/kitchen/breakfast/protos/CerealBox.proto
- [x] projects/objects/kitchen/breakfast/protos/HoneyJar.proto
- [x] projects/objects/kitchen/breakfast/protos/JamJar.proto
- [x] projects/objects/kitchen/components/protos/HotPlate.proto
- [x] projects/objects/kitchen/components/protos/Sink.proto
- [x] projects/objects/kitchen/components/protos/Worktop.proto
- [x] projects/objects/kitchen/fridge/protos/Fridge.proto
- [x] projects/objects/kitchen/oven/protos/Oven.proto
- [x] projects/objects/kitchen/utensils/protos/Carafe.proto
- [x] projects/objects/kitchen/utensils/protos/Cookware.proto
- [x] projects/objects/kitchen/utensils/protos/Fork.proto
- [x] projects/objects/kitchen/utensils/protos/Glass.proto
- [x] projects/objects/kitchen/utensils/protos/Knife.proto
- [x] projects/objects/kitchen/utensils/protos/Lid.proto
- [x] projects/objects/kitchen/utensils/protos/Plate.proto
- [x] projects/objects/kitchen/utensils/protos/Spoon.proto
- [x] projects/objects/kitchen/utensils/protos/Wineglass.proto
- [x] projects/objects/kitchen/utensils/protos/WoodenSpoon.proto
- [x] projects/objects/lego/protos/LegoLargeMotor.proto
- [x] projects/objects/lego/protos/LegoWheel.proto
- [x] projects/objects/lights/protos/CeilingLight.proto
- [x] projects/objects/lights/protos/CeilingSpotLight.proto
- [x] projects/objects/lights/protos/ConstructionLamp.proto
- [x] projects/objects/lights/protos/DoubleFluorescentLamp.proto
- [x] projects/objects/lights/protos/FloorLight.proto
- [x] projects/objects/living_room_furniture/protos/Armchair.proto
- [x] projects/objects/living_room_furniture/protos/Carpet.proto
- [x] projects/objects/living_room_furniture/protos/Sofa.proto
- [x] projects/objects/mirror/protos/Mirror.proto
- [x] projects/objects/obstacles/protos/OilBarrel.proto
- [x] projects/objects/obstacles/protos/Ramp30deg.proto
- [x] projects/objects/paintings/protos/LandscapePainting.proto
- [x] projects/objects/paintings/protos/PortraitPainting.proto
- [x] projects/objects/panels/protos/Panel.proto
- [x] projects/objects/panels/protos/PanelWithTubes.proto
- [x] projects/objects/plants/protos/BunchOfSunFlowers.proto
- [x] projects/objects/plants/protos/FlowerPot.proto
- [x] projects/objects/plants/protos/PottedTree.proto
- [x] projects/objects/road/protos/AddLaneRoadSegment.proto
- [x] projects/objects/road/protos/AddLanesRoadSegment.proto
- [x] projects/objects/road/protos/CrashBarrier.proto
- [x] projects/objects/road/protos/Crossroad.proto
- [x] projects/objects/road/protos/CurvedRoadSegment.proto
- [x] projects/objects/road/protos/HelicoidalRoadSegment.proto
- [x] projects/objects/road/protos/LaneSeparation.proto
- [x] projects/objects/road/protos/RoadIntersection.proto
- [x] projects/objects/road/protos/RoadLine.proto
- [x] projects/objects/road/protos/RoadPillars.proto
- [x] projects/objects/road/protos/Road.proto
- [x] projects/objects/road/protos/Roundabout.proto
- [x] projects/objects/road/protos/StraightRoadSegment.proto
- [x] projects/objects/robotstadium/protos/RobotstadiumGoal.proto
- [x] projects/objects/robotstadium/protos/RobotstadiumSoccerField.proto
- [x] projects/objects/rocks/protos/Rock10cm.proto
- [x] projects/objects/rocks/protos/Rock17cm.proto
- [x] projects/objects/school_furniture/protos/Blackboard.proto
- [x] projects/objects/school_furniture/protos/Book.proto
- [x] projects/objects/school_furniture/protos/Clock.proto
- [x] projects/objects/shapes/protos/TexturedBoxShape.proto
- [x] projects/objects/solids/protos/SolidBox.proto
- [x] projects/objects/solids/protos/SolidPipe.proto
- [x] projects/objects/solids/protos/SolidRoundedBox.proto
- [x] projects/objects/solids/protos/SolidTorus.proto
- [x] projects/objects/stairs/protos/StraightStairsLanding.proto
- [x] projects/objects/stairs/protos/StraightStairs.proto
- [x] projects/objects/stairs/protos/StraightStairsRail.proto
- [x] projects/objects/street_furniture/protos/Atm.proto
- [x] projects/objects/street_furniture/protos/Bench.proto
- [x] projects/objects/street_furniture/protos/BusStop.proto
- [x] projects/objects/street_furniture/protos/ClothRecyclingContainer.proto
- [x] projects/objects/street_furniture/protos/DrinkingFountain.proto
- [x] projects/objects/street_furniture/protos/ElectricalCabinet.proto
- [x] projects/objects/street_furniture/protos/EmergencyPhone.proto
- [x] projects/objects/street_furniture/protos/Fence.proto
- [x] projects/objects/street_furniture/protos/FireHydrant.proto
- [x] projects/objects/street_furniture/protos/Fountain.proto
- [x] projects/objects/street_furniture/protos/GlassRecyclingContainer.proto
- [x] projects/objects/street_furniture/protos/GuardShelter.proto
- [x] projects/objects/street_furniture/protos/IceFreezerContainer.proto
- [x] projects/objects/street_furniture/protos/Mailbox.proto
- [x] projects/objects/street_furniture/protos/MetallicTrash.proto
- [x] projects/objects/street_furniture/protos/NewsStand.proto
- [x] projects/objects/street_furniture/protos/OldBench.proto
- [x] projects/objects/street_furniture/protos/PhoneBooth.proto
- [x] projects/objects/street_furniture/protos/PublicBin.proto
- [x] projects/objects/street_furniture/protos/PublicToilet.proto
- [x] projects/objects/street_furniture/protos/SimpleBench.proto
- [x] projects/objects/street_furniture/protos/SmallKiosk.proto
- [x] projects/objects/street_furniture/protos/SnackStand.proto
- [x] projects/objects/street_furniture/protos/StoneBench.proto
- [x] projects/objects/street_furniture/protos/StoneFountain.proto
- [x] projects/objects/street_furniture/protos/TrashBin.proto
- [x] projects/objects/street_furniture/protos/TrashContainer.proto
- [x] projects/objects/street_furniture/protos/UndergroundContainer.proto
- [x] projects/objects/street_furniture/protos/UrbanFence.proto
- [x] projects/objects/street_furniture/protos/WorkTrashContainer.proto
- [x] projects/objects/tables/protos/Desk.proto
- [x] projects/objects/tables/protos/RoundTable.proto
- [x] projects/objects/tables/protos/Table.proto
- [x] projects/objects/telephone/protos/OfficeTelephone.proto
- [x] projects/objects/telephone/protos/Telephone.proto
- [x] projects/objects/television/protos/Television.proto
- [x] projects/objects/toys/protos/PaperBoat.proto
- [x] projects/objects/toys/protos/RubberDuck.proto
- [x] projects/objects/traffic/protos/CautionPanel.proto
- [x] projects/objects/traffic/protos/CautionSign.proto
- [x] projects/objects/traffic/protos/ControlledStreetLight.proto
- [x] projects/objects/traffic/protos/CrossRoadsTrafficLight.proto
- [x] projects/objects/traffic/protos/DirectionPanel.proto
- [x] projects/objects/traffic/protos/DivergentIndicator.proto
- [x] projects/objects/traffic/protos/ExitPanel.proto
- [x] projects/objects/traffic/protos/ExitSign.proto
- [x] projects/objects/traffic/protos/GenericTrafficLight.proto
- [x] projects/objects/traffic/protos/HighwayPole.proto
- [x] projects/objects/traffic/protos/HighwaySign.proto
- [x] projects/objects/traffic/protos/OrderPanel.proto
- [x] projects/objects/traffic/protos/OrderSign.proto
- [x] projects/objects/traffic/protos/ParkingLines.proto
- [x] projects/objects/traffic/protos/ParkingMeter.proto
- [x] projects/objects/traffic/protos/PedestrianCrossing.proto
- [x] projects/objects/traffic/protos/Pole.proto
- [x] projects/objects/traffic/protos/RectangularPanel.proto
- [x] projects/objects/traffic/protos/SignPole.proto
- [x] projects/objects/traffic/protos/SpeedLimitPanel.proto
- [x] projects/objects/traffic/protos/SpeedLimitSign.proto
- [x] projects/objects/traffic/protos/StopPanel.proto
- [x] projects/objects/traffic/protos/StopSign.proto
- [x] projects/objects/traffic/protos/StreetLight.proto
- [x] projects/objects/traffic/protos/TrafficCone.proto
- [x] projects/objects/traffic/protos/WorkBarrier.proto
- [x] projects/objects/traffic/protos/YieldPanel.proto
- [x] projects/objects/traffic/protos/YieldSign.proto
- [x] projects/objects/trees/protos/BigSassafras.proto
- [x] projects/objects/trees/protos/Cypress.proto
- [x] projects/objects/trees/protos/Forest.proto
- [x] projects/objects/trees/protos/Oak.proto
- [x] projects/objects/trees/protos/PalmTree.proto
- [x] projects/objects/trees/protos/Pine.proto
- [x] projects/objects/trees/protos/Sassafras.proto
- [x] projects/objects/trees/protos/SimpleTree.proto
- [x] projects/objects/trees/protos/Tree.proto

**Not added**
- projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
- projects/objects/backgrounds/protos/TexturedBackground.proto
- projects/objects/geometries/protos/Extrusion.proto
- projects/objects/geometries/protos/Rectangle.proto
- projects/objects/geometries/protos/TexturedBox.proto
- projects/objects/geometries/protos/TexturedParallelepiped.proto
- projects/objects/traffic/protos/TrafficLightBigPole.proto
- projects/objects/traffic/protos/TrafficLightHorizontal.proto
- projects/objects/traffic/protos/TrafficLight.proto
- projects/objects/traffic/protos/TrafficLightArrowLampGeometry.proto
- projects/objects/traffic/protos/TrafficLightStandardLampGeometry.proto

### CODE REVIEW

**Comment by omichel** [comment]
Why didn't you add the traffic light protos?

**Comment by omichel** [comment]
We should replace the URLs of the documentation to target the develop branch before merging this PR, right?

**Comment by BenjaminDeleze** [comment]
> We should replace the URLs of the documentation to target the develop branch before merging this PR, right?

Oops right, I just did it, but I replaced it directly with the released one so that we don't need to change it again after that (that what we did for the other protos)

**Review by omichel — APPROVED** [review]
It looks good to me. Thank you.

**Pull request merged**
