### PR TITLE
Upgraded clang-format to version 9 on appveyor

### PR DESCRIPTION
**Pull request by omichel**
Use version 9 of clang-format on appveyor

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by omichel** [comment]
To make it work, we have to make a complete update of MSYS2 which actually takes 5 minutes, thus the simplest source test takes 10 minutes instead of 5...
Therefore, I believe we should use clang-format 8 on the quick automatic test and clang-format 9 on the nightly source test.

**Comment by omichel** [comment]
clang-format is now passing, but cppcheck fails. I will wait until  #1031 is merged in revision to re-sync this branch with revision and complete this PR.

**Comment by omichel** [comment]
Now all the tests are passing.

👍

**Pull request merged**
