### PR TITLE
Python webots_distro

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Address #571 and switch `webots_distro` to Python.

Other than simplifying code this will also fix issues using OpenSSL deprecated functions.

### CODE REVIEW

**Comment by omichel** [comment]
Maybe related to #1075.

**Comment by stefaniapedrazzi** [comment]
To make the Webots R2022b run on Windows on my system I have to copy the `msys64/mingw64/share/qt6/plugins/platforms/qwindows.dll` file in the parent folder (i.e.`msys64/mingw64/share/qt6/plugins/`)

**Comment by stefaniapedrazzi** [comment]
There was a patch in `scripts/packaging/copy_msys64_files.py` to solve this issue and removed when switching to Qt6 (#4189).

**Comment by stefaniapedrazzi** [comment]
> There was a patch in scripts/packaging/copy_msys64_files.py to solve the Windows issue and removed when switching to Qt6 (https://github.com/cyberbotics/webots/pull/4189).

It seems that something similar is also needed for the TLS plugins on Windows.
And still there are issue downloading the resources from the installed program.

However, I'm getting the exact same issue with the nightly build of Windows 2022b.

**Pull request merged**
