### PR TITLE
Fix Invalid MATLAB Controller Function Prototypes

### PR DESCRIPTION
**Pull request by gokulp01**
**Description**
Fix Invalid MATLAB Controller Function Prototypes for Arrays essentially solving #1642

**Related Issues**
#1642 

**Tasks**
  - [x] Fix Documentation of the guide

**Documentation**
https://cyberbotics.com/doc/guide/controller-programming?tab-language=matlab#reading-sensors

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
Nice! Could you please fix for the other files as well. Here is the list of occurrences (that may not be exhaustive):
```
11 results - 8 files

webots • docs/guide/controller-programming.md:
  283: [x y z] = wb_gps_get_values(tag)
  284: [x y z] = wb_accelerometer_get_values(tag)
  285: [x y z] = wb_gyro_get_values(tag)

webots • docs/reference/accelerometer.md:
  114: [x y z] = wb_accelerometer_get_values(tag)

webots • docs/reference/compass.md:
  114: [x y z] = wb_compass_get_values(tag)

webots • docs/reference/gps.md:
  129: [x y z] = wb_gps_get_values(tag)

webots • docs/reference/gyro.md:
  112: [x y z] = wb_gyro_get_values(tag)

webots • docs/reference/receiver.md:
  510: [x y z] = wb_receiver_get_emitter_direction(tag)

webots • docs/reference/supervisor.md:
  2896: [x y z] = wb_supervisor_field_get_sf_vec3f(field)
  2905: [x y z] = wb_supervisor_field_get_mf_vec3f(field, index)

webots • docs/reference/touchsensor.md:
  192: [x y z] = wb_touch_sensor_get_values(tag)
```

**Comment by gokulp01** [comment]
Yeah sure! I'll fix them right away :) and I'll look around if there are any more bugs as well

**Comment by lukicdarkoo** [comment]
Here is a more complete list:
```
18 results - 9 files

webots • docs/guide/controller-programming.md:
  283: [x y z] = wb_gps_get_values(tag)
  284: [x y z] = wb_accelerometer_get_values(tag)
  285: [x y z] = wb_gyro_get_values(tag)

webots • docs/reference/accelerometer.md:
  114: [x y z] = wb_accelerometer_get_values(tag)

webots • docs/reference/compass.md:
  114: [x y z] = wb_compass_get_values(tag)

webots • docs/reference/gps.md:
  129: [x y z] = wb_gps_get_values(tag)

webots • docs/reference/gyro.md:
  112: [x y z] = wb_gyro_get_values(tag)

webots • docs/reference/inertialunit.md:
  131: [roll pitch yaw] = wb_inertial_unit_get_roll_pitch_yaw(tag)

webots • docs/reference/receiver.md:
  510: [x y z] = wb_receiver_get_emitter_direction(tag)

webots • docs/reference/supervisor.md:
  2895: [x y] = wb_supervisor_field_get_sf_vec2f(field)
  2896: [x y z] = wb_supervisor_field_get_sf_vec3f(field)
  2897: [x y z alpha] = wb_supervisor_field_get_sf_rotation(field)
  2898: [r g b] = wb_supervisor_field_get_sf_color(field)
  2904: [x y] = wb_supervisor_field_get_mf_vec2f(field, index)
  2905: [x y z] = wb_supervisor_field_get_mf_vec3f(field, index)
  2906: [x y z a] = wb_supervisor_field_get_mf_rotation(field, index)
  2907: [r g b] = wb_supervisor_field_get_mf_color(field, index)

webots • docs/reference/touchsensor.md:
  192: [x y z] = wb_touch_sensor_get_values(tag)
```
(this one is greped with ` [a-z]{1,}\] = wb_`)

**Comment by gokulp01** [comment]
@lukicdarkoo 
wb_supervisor_field_set_mf_vec2f(field, index, [x y])
wb_supervisor_field_set_mf_vec3f(field, index, [x y z])
wb_supervisor_field_set_mf_rotation(field, index, [x y z a])
wb_supervisor_field_set_mf_color(field, index, [r g b])

even these should be changed right

**Comment by gokulp01** [comment]
@lukicdarkoo @DavidMansolino Shall I close this PR? I've taken care of all the changes in #1667 including the ones in this, it will keep things a bit more clean :)

**Comment by lukicdarkoo** [comment]
> @lukicdarkoo
> webots • docs/reference/supervisor.md:
> 3074: wb_supervisor_field_set_mf_vec2f(field, index, [x y])
> 3075: wb_supervisor_field_set_mf_vec3f(field, index, [x y z])
> 3076: wb_supervisor_field_set_mf_rotation(field, index, [x y z a])
> 3077: wb_supervisor_field_set_mf_color(field, index, [r g b])
> 
> even these should be changed right

Those can be interpreted by Matlab, so I think those are fine, @omichel?

**Comment by gokulp01** [comment]
> > @lukicdarkoo
> > webots • docs/reference/supervisor.md:
> > 3074: wb_supervisor_field_set_mf_vec2f(field, index, [x y])
> > 3075: wb_supervisor_field_set_mf_vec3f(field, index, [x y z])
> > 3076: wb_supervisor_field_set_mf_rotation(field, index, [x y z a])
> > 3077: wb_supervisor_field_set_mf_color(field, index, [r g b])
> > even these should be changed right
> 
> Those can be interpreted by Matlab, so I think those are fine, @omichel?

AFAIK, some basic checks tell me, Matlab doesn't interpret them
Screenshot from 2020-05-14 16-27-54

Not sure but I might be wrong here

**Comment by omichel** [comment]
That works:
```MATLAB
>> x = 1

x =

     1

>> y = 2

y =

     2

>> [ x y ]

ans =

     1     2
```

**Comment by gokulp01** [comment]
> That works:
> 
> ```matlab
> >> x = 1
> 
> x =
> 
>      1
> 
> >> y = 2
> 
> y =
> 
>      2
> 
> >> [ x y ]
> 
> ans =
> 
>      1     2
> ```

Yes, my bad. Reverted back. Fixed all of them in #1667

**Comment by omichel** [comment]
Yes, please close this PR as it seems duplicate with #1667.

**Pull request closed without merging**
