### PR TITLE
fixed mIsOmnidirectional in WbObjectDetection

### PR DESCRIPTION
**Pull request by TheMangalex**
**Description**
Changes the calculation of mIsOmniDirectional to horizontalFov > pi / 2.

**Related Issues**
This pull-request fixes issue #6395

**Additional context**
Details on how the spherical projections were wrong before can be seen in #6395

### CODE REVIEW

**Review by omichel — CHANGES_REQUESTED** [review]
Thank you!
May I kindly ask you to add a line in the [changelog](https://github.com/Adman/webots/edit/fix-getemitterdirection/docs/reference/changelog-r2023.md) under "Bug fixes"?

**Comment by TheMangalex** [comment]
Does this work for you?
https://github.com/cyberbotics/webots/pull/6396/commits/f650732e9de7fd76454b2c4a310ade49db38ef16

**Review by omichel — CHANGES_REQUESTED** [review]
It looks good to me, but I believe [this test](https://github.com/cyberbotics/webots/blob/f650732e9de7fd76454b2c4a310ade49db38ef16/src/webots/nodes/utils/WbObjectDetection.cpp#L423) could be also simplified now.

**Comment by TheMangalex** [comment]
That seems to be the case. I adapted it and used M_PI_2 instead of M_PI / 2.0 in the initial change now to remove the additional computation and stick to the use of M_PI_2.

**Review by omichel — APPROVED** [review]
That looks very good to me now.
Thank you!

**Comment by omichel** [comment]
@TheMangalex: This PR apparently broke the [camera_recognition](https://github.com/cyberbotics/webots/blob/master/tests/api/worlds/camera_recognition.wbt) test, see: https://github.com/cyberbotics/webots/actions/runs/6386382958/job/17333860294#step:7:1254
May I kindly ask you to look into this and check the [camera_recognition](https://github.com/cyberbotics/webots/blob/master/tests/api/controllers/camera_recognition/camera_recognition.c) controller to understand why the test fails and eventually fix it?

**Comment by TheMangalex** [comment]
I'll try to look into it in the following days

**Comment by TheMangalex** [comment]
It seems that this broke the test for cylindrical projections which seem to be handled similar to spherical projections in this case..


Before PR:
webots_test_prev

After PR:
webots_test_fix

It seems to be a different issue which was created by this change, as the issue of close objects also existed for cylindrical cameras:
image


I'll have a deeper look, what causes this

**Comment by omichel** [comment]
Thank you for investigating this.

**Comment by TheMangalex** [comment]
I created #6403 as a draft which seems to fix the test and #6395 
In this PR I also added another object to the recognition test which is perpendicular to the camera sensor plane and only partially seen, as this was a problem in #6395

I want to add another test which specifically checks for the error which was fixed in #6395 , so I'll come back to this tomorrow.

**Pull request merged**
