### PR TITLE
webots.min.js: enhancement web interface toolbar

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Address #928:
* [x] improve simulation mode buttons and use the same icons as the Webots ones
* [x] improve world selection drop-down list

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by omichel** [comment]
I am wondering if the behavior of the "fast" button in the web interface is the same as in Webots (e.g., black display and run as fast as possible) or is it equivalent to the "run" button?

**Comment by stefaniapedrazzi** [comment]
The "fast" button in the web interface sets the Webots simulation mode to "fast".
https://github.com/cyberbotics/webots/blob/f743e2f0d03c6bfaa6a01b6bd169ba39b3124148/src/webots/gui/WbStreamingServer.cpp#L412

**Comment by stefaniapedrazzi** [comment]
I agree that the choice of the icon is arguable (fast vs. run) given that in the web interface the scene is rendered in any case.

But in any case the icon should match the button name.

**Comment by stefaniapedrazzi** [comment]
Ok, so I will rename the button (and everything related to it) to run and change the icon.
Note that currently this button is not visible in any of the default application we provide but only for custom solution.

**Comment by stefaniapedrazzi** [comment]
I changed the target branch to develop because changing the flag name from `webots.showFast` to `webots.showRun` could break the compatibility.

:+1:

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
