### PR TITLE
Feature web terminal

### LINKED ISSUE #818: webots.min.js: ANSI escape code not processed when printing on the console
ANSI escape codes are handled in the Webots console but not in the webots.min.js console.

**Steps to Reproduce**
1. Stream the `camera.wbt`
2. Connect with the `streaming_viewer/index.html`
3. Check the text printed in the console

Instead of changing the color of the text, the ANSI escape codes are written as text in the console
```
[camera] Looks like I found a [32mgreen[0m blob.

[camera] Looks like I found a [34mblue[0m blob.
```

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
**Description**
Add a non-interactive terminal to the toolbar:

- Display messages from stdout and stderr
- Has a `clear` function.
- Sort function by std (stdout or stderr) and tag (`INFO:`, `ERROR:`, `WARNING:`, other)
- Support ANSI escape code (Fix #818)

To test it you can:

- Test locally (change the link to `WebotsView.js` in `streaming_viewer/index.html` and the link to `toolbar.css` in `wwi/WebotsView.js`)
- Test on a docker: https://benjamindeleze.github.io/sandbox/Theia_Cloud/maze_runner/index.html
- Test remotely by changing the link to `WebotsView.js` in `streaming_viewer/index.html` from `R2022b` to `testingTerminal`

### CODE REVIEW

**Comment by BenjaminDeleze** [comment]
I changed the target branch to develop as we have released R2022b

**Comment by stefaniapedrazzi** [comment]
Is there any particular reason why the new "clear" icon has the PNG format and the other icons ("fullscreen", "ide", "info", ..) are stored in SVG format.
It would be better to be consistent with the format.

**Review by stefaniapedrazzi — CHANGES_REQUESTED** [review]

**Comment by stefaniapedrazzi** [comment]
Everything works fine!

It took me a while to make it work locally, I double checked that I'm loading the modified CSS but from what I could get locally I think the layout can be improved:
* the clear / bin icon is not vertically centered with the toolbar
* maybe also the buttons labels (stdout, stderr, etc.) can be centered a little bit more vertically
* padding missing around the "stdout", "stderr" and "other" labels
* I would personally remove the colon from "INFO:", "ERROR:" and "WARNING:" but it's ok to keep them

Screenshot from 2022-09-20 21-12-08

**Comment by BenjaminDeleze** [comment]
> Everything works fine!
> 
> It took me a while to make it work locally, I double checked that I'm loading the modified CSS but from what I could get locally I think the layout can be improved:
> 
> * the clear / bin icon is not vertically centered with the toolbar
> * maybe also the buttons labels (stdout, stderr, etc.) can be centered a little bit more vertically
> * padding missing around the "stdout", "stderr" and "other" labels
> * I would personally remove the colon from "INFO:", "ERROR:" and "WARNING:" but it's ok to keep them
> 
> Screenshot from 2022-09-20 21-12-08

Wow you're right the layout seems ugly. I retested and everything looks fine on Chrome but not on Firefox :(

**Comment by BenjaminDeleze** [comment]
I think I addressed all comments (I am not sure about what you meant by "padding missing around the "stdout", "stderr" and "other" labels")

**Comment by stefaniapedrazzi** [comment]
Ok, I will review the changed.
I meant that there is some "space" between the word and the button border for "INFO", "WARNING" and "ERROR" but not for "stdout" "stderr" and "others".

**Comment by BenjaminDeleze** [comment]
Thank, I will fix that right now

**Comment by stefaniapedrazzi** [comment]
I confirmed the layout issues are fixed.

Just a question: in Webots the console is cleared when a world is loaded.
Maybe it would be good to implement the same behavior in the web interface and clear the terminal when loading a world.

**Comment by BenjaminDeleze** [comment]
Good idea, I will do it

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Pull request merged**
