### PR TITLE
Convert Tinkerbots to FLU

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
PROTOs:
* [x] (701) robots/kinematics/tinkerbots/protos/TinkerbotsBrickAdapter.proto
* [x] (702) robots/kinematics/tinkerbots/protos/TinkerbotsPivot.proto
* [x] (703) robots/kinematics/tinkerbots/protos/TinkerbotsCubieMaleCube.proto
* [x] (704) robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithRoundSlots.proto
* [x] (705) robots/kinematics/tinkerbots/protos/TinkerbotsPlasticAppearance.proto
* [x] (706) robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithCrossSlots.proto
* [x] (707) robots/kinematics/tinkerbots/protos/TinkerbotsCubieTriangle.proto
* [x] (708) robots/kinematics/tinkerbots/protos/TinkerbotsAxle.proto
* [x] (709) robots/kinematics/tinkerbots/protos/TinkerbotsFinger.proto
* [x] (710) robots/kinematics/tinkerbots/protos/TinkerbotsWheel.proto
* [x] (711) robots/kinematics/tinkerbots/protos/TinkerbotsGrabber.proto
* [x] (712) robots/kinematics/tinkerbots/protos/TinkerbotsMotor.proto
* [x] (713) robots/kinematics/tinkerbots/protos/TinkerbotsCube.proto
* [x] (714) robots/kinematics/tinkerbots/protos/TinkerbotsCubiePyramid.proto
* [x] (715) robots/kinematics/tinkerbots/protos/TinkerbotsBase.proto
* [x] (716) robots/kinematics/tinkerbots/protos/TinkerbotsTwister.proto
* [x] (717) robots/kinematics/tinkerbots/protos/TinkerbotsLightSensor.proto
* [x] (718) robots/kinematics/tinkerbots/protos/TinkerbotsCubieFemaleCube.proto
* [x] (719) robots/kinematics/tinkerbots/protos/TinkerbotsDistanceSensor.proto
* [x] (720) robots/kinematics/tinkerbots/protos/TinkerbotsLEDAppearance.proto

worlds:
* [x] (256) projects/robots/kinematics/tinkerbots/worlds/vision_car.wbt
* [x] (257) projects/robots/kinematics/tinkerbots/worlds/sensoric_mega_set.wbt
* [x] (258) projects/robots/kinematics/tinkerbots/worlds/grabber_base.wbt
* [x] (259) projects/robots/kinematics/tinkerbots/worlds/roadster.wbt
* [x] (260) projects/robots/kinematics/tinkerbots/worlds/racer.wbt
* [x] (261) projects/robots/kinematics/tinkerbots/worlds/braitenberg.wbt
* [x] (262) projects/robots/kinematics/tinkerbots/worlds/donnergugi.wbt
* [x] (263) projects/robots/kinematics/tinkerbots/worlds/top_dog.wbt
* [x] (264) projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
* [x] (265) projects/robots/kinematics/tinkerbots/worlds/android_l30.wbt

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
The up/down/left/right/front/back slots seem to be correctly positioned, but robots based on `TinkerbotsBase` are not FLU. I believe we should fix it.

**Comment by stefaniapedrazzi** [comment]
> The up/down/left/right/front/back slots seem to be correctly positioned, but robots based on TinkerbotsBase are not FLU. I believe we should fix it.

TinkerbotsBase PROTO is FLU.
Robots built on this can be oriented in any way and it differs from robot to robot.
If you check the "android_l30.wbt", then the robot is FLU.

**Comment by lukicdarkoo** [comment]
> TinkerbotsBase PROTO is FLU.

It looks good.

> Robots built on this can be oriented in any way and it differs from robot to robot and we cannot fix it for all the cases.

Why not? Without the `android_l30.wbt` world there are 9 left. There are not many such robots?

**Comment by stefaniapedrazzi** [comment]
> Why not? Without the android_l30.wbt world there are 9 left. There are not many such robots?

Because the root is the TinkerbotBase PROTO. This is the basic principle of modular Tinkerbots robots.
The only way to change the robot modeled with Tinkerbots parts to FLU is to modify the TinkerbotsBase PROTO.
But if you do it, then it will break the orientation of other robots.

**Review by lukicdarkoo — APPROVED** [review]
I see, e.g. there is no `frontSlot` in `TinkerbotBase`, and shuffling slots around would break a lot of things.

Looks good to me, thank you

**Pull request merged**
