### PR TITLE
Update to Discord API 1.5.0

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Update to Discord API 1.5.0

### CODE REVIEW

**Comment by DavidMansolino** [comment]
It seems the bot now requires some privileges to get the member roles:

> discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

@omichel can you check (https://discord.com/developers/applications) if you can enable the 'privileged intents' for the bot?

**Comment by omichel** [comment]
Done:
image

**Comment by DavidMansolino** [comment]
> Done:
> image

Thank you, it seems it worked fine.

**Comment by DavidMansolino** [comment]
Replaced by #2308.

**Pull request closed without merging**
