### PR TITLE
Make bash scripts exit when any command fails.

### PR DESCRIPTION
**Pull request by brettle**
This should make failing builds fail faster.

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Thank you.

**Comment by omichel** [comment]
This PR is causing the scripts to fail when running them on a Ubuntu 20.04 machine whereas it used to work (as some errors can be safely ignored). I will provide a fix in a new PR.

**Comment by brettle** [comment]
Sorry about that. I'd figured such problems would be caught during CI.

**Comment by omichel** [comment]
No problem. Such things happen every day.

**Pull request merged**
