### PR TITLE
Update supervisor.md

### PR DESCRIPTION
**Pull request by bkpcoding**
Yeah, sorry for PR in the master branch, I have made this PR for the released branch, this PR solves issue#2788.

**Description**
Its fixes a typo in the documentation of supervisor.md in C++ part of the code of the programming fundamentals/supervisor programming/Introduction code of the webots documentation.

**Related Issues**
This pull-request fixes issue #2788

**Documentation**
https://github.com/cyberbotics/webots/blob/released/docs/guide/supervisor-programming.md?version=released

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Thank you.
FYI, the link to your modified version of the documentation is this: https://cyberbotics.com/doc/guide/supervisor-programming?version=bkpcoding:patch-2&tab-language=c++#tracking-the-position-of-robots

You should now be able to merge your PR.

**Comment by omichel** [comment]
May I let you press the "Squash and merge" green button?

**Comment by omichel** [comment]
You should be able to do it after accepting my invitation to the Committers group (check your inbox).

**Comment by bkpcoding** [comment]
Thanks, @omichel, I have accepted the invitation. Will surely work hard towards other issues and will try to get a feature up by the end of this month :) And I have squashed and merged the PR.

**Pull request merged**
