### PR TITLE
Fix pointer in Matlab API

### LINKED ISSUE #2316: Matlab Supervisor API functions return pointers
**Describe the Bug**
Some of the Matlab API functions of the Supervisor return non-native Matlab array, e.g.:
https://github.com/cyberbotics/webots/blob/master/lib/controller/matlab/wb_supervisor_node_get_velocity.m#L6

Instead, their returned value should be converted to an array, e.g.:
https://github.com/cyberbotics/webots/blob/master/lib/controller/matlab/wb_supervisor_field_get_sf_vec3f.m#L6-L8

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix #2316

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Thank you.
I assume this is the only method which has this problem, did you check them all?

**Review by omichel — CHANGES_REQUESTED** [review]
We should probably comment out the corresponding line in the `mgenerate.py` script.

**Comment by stefaniapedrazzi** [comment]
Yes, I checked all the methods and all the others are correct.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
