### PR TITLE
Fix cadshape move to viewpoint

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
The `recomputeBoundingSphere` function in `WbCadShape` was called in a different place than in `WbGroup` and `WbGeometry` and I could not find out why.

This causes, since https://github.com/cyberbotics/webots/pull/5359, the `move Viewpoint to Object` to not work.

@ad-daniel maybe you remember why it was done differently in `WbCadShape`?

### CODE REVIEW

**Comment by ad-daniel** [comment]
No reason that I can think of, likely thought it didn't matter which in practice it seems to

**Review by ad-daniel — CHANGES_REQUESTED** [review]
Actually I think I know why it was defined this way, the reason is that I used WbSkin as a template when defining CadShape, as such if this was broken, that one is likely to be too

**Comment by BenjaminDeleze** [comment]
> Actually I think I know why it was defined this way, the reason is that I used WbSkin as a template when defining CadShape, as such if this was broken, that one is likely to be too

I justed tested with the `sample/devices/worlds/skin.wbt` and I could move to Skin without problem.

**Review by ad-daniel — APPROVED** [review]
Thank you

**Pull request merged**
