### PR TITLE
Update github links for .proto visualization on webots.cloud.

### PR DESCRIPTION
**Pull request by SarvagyaVaish**
**Description**
Links in documentation markdown files referring to proto files for visualization on webots.cloud use the incorrect github base URL. Instead of ".../tree/...", it should be ".../blob/...". This PR makes that change and updates the docs. 

**Related Issues**
This pull-request fixes issue discussed in https://github.com/cyberbotics/webots/discussions/6463

**Tasks**
Add the list of tasks of this PR.
  - [x] Create a new variable called `github_blob` to be used in the markdown docs.
  - [x] Update markdown files to use this new variable.

**Documentation**
(need help)
If this pull-request changes the doc, add the link to the related page, including the `?version=BRANCH_NAME`, such as:
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=develop

**Screenshots**
N/A
If this pull-request includes any new robots/simulations/etc. add one or more screenshots of the result.

**Additional context**
N/A
Add any other context about the pull-request here.

### CODE REVIEW

**Comment by SarvagyaVaish** [comment]
@omichel, will the docs get generated as part of the CI steps? That would be the easiest way to test these changes out.

**Comment by omichel** [comment]
You can see your documentation page [here](https://cyberbotics.com/doc/automobile/proto-nodes?version=SarvagyaVaish:fix-github-tree-blob) and it looks correct. However, the link is not working because your branch is not on the main repository, but once merged it should work.

**Review by omichel — APPROVED** [review]
That looks very good to me.
Thank you for this nice fix!

**Review by omichel — CHANGES_REQUESTED** [review]
In order to make it live as soon as it is merged, we should make a new PR with these changes targeting the "released" branch instead of the "master" branch.

**Comment by SarvagyaVaish** [comment]
Updates this PR to target `released`, instead of `main`.

**Review by omichel — APPROVED** [review]
Great, thanks.

**Comment by SarvagyaVaish** [comment]
Will you handle merging ‘released’ into ‘master’ soon?

**Comment by omichel** [comment]
> Will you handle merging ‘released’ into ‘master’ soon?

Yes, we have a nightly GitHub action taking care of this, so it should be done in the next 24 hours. Then, it will also be semi-automatically back-ported to the develop branch as well.

**Comment by SarvagyaVaish** [comment]
Oh nice!!

**Comment by omichel** [comment]
See #6466.

**Pull request merged**
