### PR TITLE
Fix Windows Compilation and Nightly

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Fixed the nightly failures on AppVeyor.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
The appveyor nightly are working again: https://github.com/cyberbotics/webots/releases/tag/nightly_28_1_2020

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
Although the nightly build were compiling, the local build was broken if python was installed in `C:\Program Files` and Webots when installed in `C:\Program File` was not able to recompile controllers. I just fixed these two problems in my previous commit.

**Comment by omichel** [comment]
It build nicely locally and on appveyor: https://ci.appveyor.com/project/omichel/webots-master/builds/30401977
The resulting package installed in `C:\Program Files\Webots` is able to compile controllers.

**Comment by DavidMansolino** [comment]
Thank you for the improvment.

**Pull request merged**
