### PR TITLE
Added bullets

### PR DESCRIPTION
**Pull request by chaytanyasinha**
Added bullets

Description
A new user might find bullets much comfortable while reading the points under instructions.
link:https://cyberbotics.com/doc/guide/using-your-ide?version=chaytanyasinha:master

Related Issues
This pull-request fixes issue cyberbotics#1671

### CODE REVIEW

**Comment by omichel** [comment]
Thank you for this contribution!

In the original description, please provide a link allowing us to view online:
https://cyberbotics.com/doc/guide/using-your-ide?version=chaytanyasinha:master
This will allow us to review your PR more efficiently.

From a the provided link, I can see that the page layout was somehow broken by your contribution. Could you have a look at it and fix it?

**Comment by chaytanyasinha** [comment]
@omichel I have done the changes in description and I checked the link and It was working fine for me.Please correct me if I am wrong

**Comment by omichel** [comment]
Here is what I mean: your contribution look like this:
image

While the original page looks like this:
image

**Comment by chaytanyasinha** [comment]
okay @omichel I got your point and I have done the changes.

**Comment by omichel** [comment]
It now breaks item list numbering: item 6 now appears as item 1...

**Comment by chaytanyasinha** [comment]
@omichel I guess it's fine now

**Comment by chaytanyasinha** [comment]
@omichel  I think this should work.

**Comment by omichel** [comment]
Thank you!

I added a better regular tabbing for paragraphs and set one sentence per line. I also fixed the indentation of the quote block.

**Comment by chaytanyasinha** [comment]
@omichel Thanks.Actually this was my first PR to webots that's why I faced some issues.I am sorry for that.I'll do it better next time.

**Comment by omichel** [comment]
You should now be able to merge this PR by pressing the "Merge pull request" button.

**Comment by chaytanyasinha** [comment]
@omichel I thought that you'll that.

**Pull request merged**
