### PR TITLE
Update Doc

### PR DESCRIPTION
**Pull request by DavidMansolino**
We did forget to update/regenerate the documentation before releasing R2019b-rev1.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:+1:   I did remove the thumbnail test from Travis because of #840

**Comment by DavidMansolino** [comment]
Note: I also updated the release procedure: https://github.com/cyberbotics/webots/wiki/Release-Procedure/_compare/8eb2b50622a8196d8c694b4fce106fae98d9d58e...9fcc79132f0a80491bddbe1f6c1212c2d78d8417

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by DavidMansolino** [comment]
:+1:  There was still some issue with indentation.

**Pull request merged**
