### PR TITLE
Compute boundingSphere for Skin node

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Address first part of #3669:
* [x] compute the bounding sphere for the Skin node

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Only Windows test failed due to Java installation errors.

**Review by omichel — COMMENTED** [review]
The code looks good. However, when I try the skin.wbt example, select the CharacterSkin node and "Move Viewpoint to Object" menu, it doesn't seem to work properly:
skin

Moreover, while in stop mode, trying "Move Viewpoint to Object" several times on the CharacterSkin object yields alternatively to two different positions of the viewpoint, one being apparently correct and the other being apparently wrong (the one of the screenshot).

**Comment by stefaniapedrazzi** [comment]
Only the Windows test failed.

The two reported issues should now be fixed.

**Review by omichel — APPROVED** [review]
Yes, it works well now. Thank you.

**Pull request merged**
