### PR TITLE
Global variables fix in session_server.py

### PR DESCRIPTION
**Pull request by bkpcoding**
**Description**
Just tried to create a class for global variables and so as to eliminate the use of globals in the code, although left some of them like(LOAD_THRESHOLD, LOAD_REFRESH), which are mainly constants and therefore won't introduce bugs. This is not the full implementation of the code, there are somethings that I don't know like tornado, thus don't know whether adding arguments to the SessionHandler, MonitorHandler, ClientWebSocketHandler 's __init__ will affect the working of the code, any help would be appreciated. 
I Will take feedbacks positively, even if the changes are not necessary then I can focus on other bugs else if I am going in the right direction then maybe will try to make it more robust and try to implement the same for other files as well where global is used.

**Related Issues**
This pull-request fixes issue #1428

### CODE REVIEW

**Comment by bkpcoding** [comment]
I don't know why it's showing my previous commits also, but the main commit that this PR is for the session_server.py file

**Comment by omichel** [comment]
I am not convinced this PR is a progress with respect to the original code.
It adds the complexity of one extra class to get rid of two global variables, which seems overkill.

**Comment by bkpcoding** [comment]
Yeah, it did seem to me that it kind of overcomplicates the things and I was also not able to put in config global variable to it, so just something I tried out to remove global variables. Anyways thank you for your suggestion, maybe will try and fix other bugs or if you have idea about removing these global variables without overcomplicating like adding additional class then I will be more than happy to implement.

**Comment by omichel** [comment]
In case you are wondering which issue to address, I believe this one could be very useful to us: #2884. We would be happy to review your PR about it.

**Comment by bkpcoding** [comment]
Sure, @omichel I will try my best to get the PR ;)

**Pull request closed without merging**
