### PR TITLE
Rollback macOS Qt version.

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
The version 5.15.0 of Qt has some issues with button on pop-up windows.

**Related Issues**
This pull-request fixes issue #1944

### CODE REVIEW

**Comment by DavidMansolino** [comment]
I confirm the rollback of the Qt version fixed the issue.

**Comment by DavidMansolino** [comment]
:heavy_check_mark:: travis_release: https://travis-ci.com/github/cyberbotics/webots/builds/176461383

**Comment by omichel** [comment]
Since then, Qt-5.15.2 was released, which possibly fixes this bug. We should give it a new try.

**Comment by omichel** [comment]
It seems to be fixed in 5.15.1, see https://bugreports.qt.io/browse/QTBUG-85487?filter=22659&jql=project%20%3D%20QTBUG%20AND%20issuetype%20%3D%20Bug%20AND%20resolution%20in%20(Done%2C%20Fixed)%20AND%20fixVersion%20in%20(5.15.3%2C%205.15.1%2C%205.15.2)%20AND%20text%20~%20%22mac%22%20ORDER%20BY%20priority%20DESC%2C%20status%20ASC%2C%20labels%20ASC

**Pull request merged**
