### PR TITLE
Fix npm uninstall

### LINKED ISSUE #2481: Make cleanse failing for "npm" on Linux
Make "cleanse" fails on Linux at the `resources/web/wwi` folder due to wrong uninstall of the local npm packages.

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix #2481.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
All the packages have been created successfully.
I could not test on Windows and macOS.

**Comment by omichel** [comment]
I am testing in on Windows...

**Comment by stefaniapedrazzi** [comment]
Thank you

**Review by omichel — APPROVED** [review]
Thank you.
I tested both on Windows and mac OS and it works fine in both cases.
The cleanse target is more verbose than before, especially on mac OS, but that's fine.

**Pull request merged**
