### PR TITLE
Fix cppcheck 1.89 errors

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Address #1028

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Yesterday evening I ran the `travis_unit` test and everything passes except for the unit test on ubuntu 18.04 where the `mirror_supervisor` failed.

So maybe we could start reviewing this PR.

The source code of ODE was not tested, so I removed the include files of ODE too that are now throwing many errors (mainly parameters that could be const).

:+1:

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
Sorry I was reviewing for the last time before merging and I found that the new method `WbClipboard::deleteInstance` was incomplete.

:+1:

**Comment by stefaniapedrazzi** [comment]
I run the test_suite locally and found another issue with the clipboard.

:+1:

**Pull request merged**
