### PR TITLE
Fix Nao.selfCollision

### PR DESCRIPTION
**Pull request by fabienrohrer**
Reported here: https://stackoverflow.com/questions/59020010/nao-robot-sinking-into-floor-webots

Fix `Nao.selfCollision`. Internal forces were present due to the feet bounding objects causing weird shrink in floors. The touch sensors bounding objects were overlapping with the foot body.

The present Transform should be equivalent to the previous one.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
| Before | After |
| --- | --- |
| before | after |

**Comment by fabienrohrer** [comment]
👍

**Comment by W4hrsch3inlich** [comment]
Im facing a problem, where the bottom foot bounding object keeps lowering its position.

When i start the simulation:
Normal
After a while:
Bug

Any suggestions why this appears and how it could be fixed ?

**Comment by omichel** [comment]
I cannot reproduce this with the `nao_demo.wbt` of Webots R2020b revision 1, after making the robot walk for a few steps. Can you provide clear step-by-step instructions describing how we could reproduce this problem? Also, please open a complete and precise new bug report instead of writing a message in this PR.

**Pull request merged**
