### PR TITLE
Fix Distance-Sensors Reading with Cached Textures

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
Fix Distance-Sensors Reading with Cached Textures

**Related Issues**
This pull-request fixes issue #2365

### CODE REVIEW

**Comment by omichel** [comment]
The test suite is failing with distance sensor readings on textures...

**Comment by DavidMansolino** [comment]
> The test suite is failing with distance sensor readings on textures...

The test was indeed previously affected by the bug, the `WbImageTexture::pickColor` was fallbacking to (1.0, 1.0, 1.0), it is now working correctly and the value returned by the distance-sensors therefore changed.
I updated the test accordingly.

**Comment by DavidMansolino** [comment]
The test is now passing.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
