### PR TITLE
Add further protos to webots.cloud

### PR DESCRIPTION
**Pull request by BenjaminDeleze**
**Description**
As those protos have no dedicated documentation, this PR will mainly consist in `yaml` files and changing the documentation url of the `.proto`

- [x] bounding_objects
  - [x] PipeBoundingObject.proto
  - [x] TorusBoundingObject.proto
- [x] devices
  - [x] projects/devices/delphi/protos/DelphiESR.proto
  - [x] projects/devices/generic/protos/Servo.proto
  - [x] projects/devices/hokuyo/protos/HokuyoUrg04lx.proto
  - [x] projects/devices/hokuyo/protos/HokuyoUrg04lxug01.proto
  - [x] projects/devices/hokuyo/protos/HokuyoUtm30lx.proto
  - [x] projects/devices/ibeo/protos/IbeoLux.proto
  - [x] projects/devices/microsoft/protos/Kinect.proto
  - [x] projects/devices/multisense/protos/MultiSenseS21.proto
  - [x] projects/devices/nvidia/protos/JetsonNano.proto
  - [x] projects/devices/orbbec/protos/Astra.proto
  - [x] projects/devices/robotiq/protos/Robotiq3fGripper.proto
  - [x] projects/devices/robotis/protos/RobotisLds01.proto
  - [x] projects/devices/sharp/protos/SharpGP2D120.proto
  - [x] projects/devices/sharp/protos/SharpGP2Y0A02YK0F.proto
  - [x] projects/devices/sharp/protos/SharpGP2Y0A41SK0F.proto
  - [x] projects/devices/sharp/protos/SharpGP2Y0A710K0F.proto
  - [x] projects/devices/sick/protos/SickLdMrs.proto
  - [x] projects/devices/sick/protos/SickLms291.proto
  - [x] projects/devices/sick/protos/SickS300.proto
  - [x] projects/devices/slamtec/protos/RpLidarA2.proto
  - [x] projects/devices/smartmicro/protos/SmsUmrr-0a29.proto
  - [x] projects/devices/smartmicro/protos/SmsUmrr-0a30.proto
  - [x] projects/devices/smartmicro/protos/SmsUmrr-0a31.proto
  - [x] projects/devices/tdk/protos/Mpu-9250.proto
  - [x] projects/devices/velodyne/protos/VelodyneHDL-32E.proto
  - [x] projects/devices/velodyne/protos/VelodyneHDL-64E.proto
  - [x] projects/devices/velodyne/protos/VelodynePuck.proto
  - [x] projects/devices/velodyne/protos/VelodyneVLP-16.proto
- [x] humans
  - [x]  projects/humans/pedestrian/protos/Pedestrian.proto
- [x] joints
  - [x] projects/joints/protos/Hinge2JointWithBacklash.proto
  - [x] projects/joints/protos/HingeJointWithBacklash.proto
- [x] samples
  - [x] projects/samples/contests/robocup/protos/RobocupGoal.proto
  - [x] projects/samples/contests/robocup/protos/RobocupSoccerField.proto
  - [x] projects/samples/contests/tower_of_hanoi/protos/YoubotFlag.proto
  - [x] projects/samples/rendering/protos/Helmet.proto
  - [x] projects/samples/robotbenchmark/pit_escape/protos/Pit.proto
  - [x] projects/samples/tutorials/protos/FourWheelsRobot.proto
 
**Protos voluntarily not added**

- C3dViewer
- SumoDisplay
- SumoInterface
- CharacterSkin (because skin is not available in webotsJS)
- projects/samples/contests/ratslife/protos/e-puck/E-puckFlag.proto
- projects/samples/contests/ratslife/protos/LegoInterval.proto
- projects/samples/contests/ratslife/protos/LegoWall.proto
- projects/samples/contests/ratslife/protos/NXTFeeder.proto
- projects/samples/contests/rockin/protos/RoCKInAX01.proto
- projects/samples/contests/rockin/protos/RoCKInAX06.proto
- projects/samples/contests/rockin/protos/RoCKInER02.proto
- projects/samples/contests/rockin/protos/RoCKInShelf.proto
- projects/samples/curriculum/protos/Obstacle.proto
- projects/samples/rendering/protos/PingPongBallScaled.proto
- projects/samples/rendering/protos/SphereGrid.proto
- projects/samples/robotbenchmark/maze_runner/protos/MazeBlock.proto
- projects/samples/robotbenchmark/maze_runner/protos/MazeRunnerBenchmark.proto
- projects/samples/robotbenchmark/square_path/protos/SquarePathPioneer3dx.proto
- projects/samples/robotbenchmark/visual_tracking/protos/VisualTrackingBenchmark.proto
- projects/samples/robotbenchmark/wall_following/protos/WallFollowingPioneer3dx.proto$
- projects/samples/geometries/protos/TeapotMesh.proto

### CODE REVIEW

**Comment by omichel** [comment]
I suggest the following reviews:
@ygoumaz: from PipeBoundingObject.proto to RobotisLds01.proto
@ad-daniel: from SharpGP2D120.proto to VelodyneVLP-16.proto
@omichel: from Pedestrian.proto to FourWheelsRobot.proto

**Review by ygoumaz — CHANGES_REQUESTED** [review]
I have found the following problems:

* In the description of the Kinect, the names of the rangefinder and the camera are not correctly displayed:
  ```
  Microsoft Kinect. It contains a RangeFinder device called " + ' range'" and a Camera device called " + ' color'".
  ```
  Also, a Camera field is displayed in red in the description of the `cameraName` parameter when all the others are in white.

* The fields summary of the MultiSenseS21 seems incomplete.

* In addition, on most of the robots (probably all), when selecting a device in the Devices tab, it correctly shows information in the 3D preview. But when changing the value of a parameter, the device is unselected, which sometimes makes it hard to see the impact of a modification of a parameter.

**Comment by ad-daniel** [comment]
Thank you, just a PROTO issue and a detail

- SickS300: description doesn't look good: `Model of Sick S300 (lidar device). specs:`
- Velodyne 64e: logo is wrong (in webots too), the image lens image is wrong (webotsjs only). Also, is the field summary supposed to show them all? Currently doesn't mention translation/rotation (same for all velodyne)
a

**Comment by BenjaminDeleze** [comment]
> * n the description of the Kinect, the names of the rangefinder and the camera are not correctly displayed:
>   ```
>   Microsoft Kinect. It contains a RangeFinder device called " + ' range'" and a Camera device called " + ' color'".
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Also, a Camera field is displayed in red in the description of the `cameraName` parameter when all the others are in white.

Fixed, it seems like the `.md` reader is interpreting `<text>` part as something else (that is why the following `camera` was red



> * The fields summary of the MultiSenseS21 seems incomplete.
> *

The fields summary online reference fields that have a description. In the case of the `MultiSenseS21` only one is documented.



> * In addition, on most of the robots (probably all), when selecting a device in the Devices tab, it correctly shows information in the 3D preview. But when changing the value of a parameter, the device is unselected, which sometimes makes it hard to see the impact of a modification of a parameter.

It depends there is two cases:
- The parameter does not trigger a regeneration (for example changing the translation, rotation, the camera width or height of https://webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto&type=undefined). This is normally the case of most parameters.
- The parameter does trigger a regeneration. In this case, the object is destroyed and rebuilt from scratch (regenerated) and so all the ids change and some devices could be added/removed so we are forced to reset the selected devices.

**Comment by BenjaminDeleze** [comment]
> * Also, is the field summary supposed to show them all? Currently doesn't mention translation/rotation (same for all velodyne)

No, only the ones that have a description.

I don't know if it is worth adding a description as it could be a huge job if we want to do it for all fields and for all protos. Maybe only for the devices? or for some protos.
I don't know what is really useful.

**Comment by ygoumaz** [comment]
> It depends there is two cases:
> 
> * The parameter does not trigger a regeneration (for example changing the translation, rotation, the camera width or height of https://webots.cloud/run?version=R2023b&url=https://github.com/cyberbotics/webots/blob/doc-add-robots/projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto&type=undefined). This is normally the case of most parameters.
> * The parameter does trigger a regeneration. In this case, the object is destroyed and rebuilt from scratch (regenerated) and so all the ids change and some devices could be added/removed so we are forced to reset the selected devices.

It makes sense. As discussed, I don't think there really is a solution when the PROTO is regenerated, as it could totally change. Therefore it is mainly a matter of design to make sure the regeneration is triggered only when really needed.

**Review by ygoumaz — APPROVED** [review]
It seems alright to me. Thank you!

**Review by ad-daniel — APPROVED** [review]
Good for me as well

**Review by omichel — CHANGES_REQUESTED** [review]
Last request: in case the 3D representation is not available, it would be nice to display the proto icon centered just below the proto name (it may be small, like 256x256 or 128x128).

**Review by omichel — APPROVED** [review]
All good for me too.

**Pull request merged**
