### PR TITLE
Add support for multiple table types in documentation

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Currently it is only possible to create tables for the programming language because the tab option is stored in a generic "tab" GET value.
The aim of this PR is to improve the current system so that it will support multiple table options (at least programming language and operating system).

Main changes:
- when defining a `%tab-component` in the MD file, we should also specify the table title (e.g. "language", "os")
- each table type has a specific query value in the URL with `tab-` prefix(e.g. "tab-language", "tab-os")

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Unfortunately we probably have to wait until the last commit will be available on jsdelivr.

:+1:

**Comment by omichel** [comment]
:eyes: I am testing from https://www.cyberbotics.com/doc/guide/running-extern-robot-controllers?version=feature-multiple-tables-in-documentation#environment-variables.
When I select a language and an os, the language and os parameters are properly added to the URL. However, when I navigate to a different page (following a link in the doc menu), I loose the language and os parameters from the URL (but not the version parameter), so that when I come back to the original page I need to select os and language again.

**Comment by stefaniapedrazzi** [comment]
> When I select a language and an os, the language and os parameters are properly added to the URL. However, when I navigate to a different page (following a link in the doc menu), I loose the language and os parameters from the URL (but not the version parameter), so that when I come back to the original page I need to select os and language again.

Strange, I'm not getting the same (I just cleared the cache).

This is the behavior before the fix in 1c88665 but should be fixed now.

And before the last commit 29088c2 (the current version delivered by jsdelivr), there are errors when selecting a tab.

**Comment by stefaniapedrazzi** [comment]
Ok, this is correct.
To test we have to wait until jsdelivr updates the files to the latest version.

Alternatively in Chrome developer tools it is possible to modify the JS files while running them and apply manually the latest commit 29088c2

**Comment by omichel** [comment]
I cleared the jsdelivr cache as explained here: https://github.com/omichel/cyberbotics/wiki/How-to-purge-jsDelivr-cache and it now works as expected.

**Comment by DavidMansolino** [comment]
for me it is not working as expected, @omichel can you open this link: https://www.cyberbotics.com/doc/guide/running-extern-robot-controllers?version=feature-multiple-tables-in-documentation&tab-language=python#environment-variables
do you see the `python` tab as expected?

**Comment by stefaniapedrazzi** [comment]
Yes, I will check tomorrow

> I cleared the jsdelivr cache as explained here: https://github.com/omichel/cyberbotics/wiki/How-to-purge-jsDelivr-cache and it now works as expected.

Good. Yesterday even after purging the resources were not updated...

**Comment by stefaniapedrazzi** [comment]
The problem comes from `docs/doc.php` that doesn't parse correctly the version now that the tab key changed.

**Comment by stefaniapedrazzi** [comment]
Escaping the HTML special characters before extracting the queries breaks the regular expression and make it more difficult (especially for `&` that is converted to `&amp;`).

To me it seems better to first extract the book, page, branch, etc. and then make escape the HTML special characters before using these values.

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
I just fixed a couple of links that were still not working correctly:
* `tab` query with version (page not loaded):
    https://www.cyberbotics.com/doc/guide/running-extern-robot-controllers?version=master&tab=python
* old `tab` query in new `viewer.js` (tab option was ignored):
    https://www.cyberbotics.com/doc/guide/running-extern-robot-controllers?version=feature-multiple-tables-in-documentation&tab=python

Then I uploaded the the `request_method.js` file so that I could remove the test code from `viewer.js`.

**Comment by stefaniapedrazzi** [comment]
I tried to purge jsdelivr but it still doesn't work for me..

Maybe it is better to merge this PR directly in master.

**Comment by omichel** [comment]
I could purge the jsdelivr cache with https://purge.jsdelivr.net/gh/cyberbotics/webots@feature-multiple-tables-in-documentation/docs/js/viewer.js

**Comment by omichel** [comment]
You can check it at https://cdn.jsdelivr.net/gh/cyberbotics/webots@feature-multiple-tables-in-documentation/docs/js/viewer.js

**Comment by omichel** [comment]
I updated https://github.com/omichel/cyberbotics/wiki/How-to-purge-jsDelivr-cache which was still referring to omichel/webots instead of cyberbotics/webots. Maybe that's the problem you experienced?

**Comment by omichel** [comment]
Shall I update `doc.php` on the server with the new version you committed here?

**Comment by stefaniapedrazzi** [comment]
> Shall I update doc.php on the server with the new version you committed here?

Yes, thank you.

> I updated https://github.com/omichel/cyberbotics/wiki/How-to-purge-jsDelivr-cache which was still referring to omichel/webots instead of cyberbotics/webots. Maybe that's the problem you experienced?

No, I'm sure I used the correct URL.
And I just checked but I'm still getting the old version.

**Comment by omichel** [comment]
I am definitely getting the new version... Did you clear your browser cache?

**Comment by stefaniapedrazzi** [comment]
> I am definitely getting the new version... Did you clear your browser cache?

yes, even after clearing the cache (both in Chrome and Firefox) I'm still getting the old version.
But if I download the file using `wget`, then it works and i'm getting the new one..

**Comment by stefaniapedrazzi** [comment]
> So that's clearly a cache issue.

Yes, but I'm not sure it is a cache issue at my browser level.
I tried from a virtual machine and I get the exact same old file.

**Pull request merged**
