### PR TITLE
Fix fields order in openai_gym.wbt

### PR DESCRIPTION
**Pull request by DavidMansolino**
This is making the nightly world update test fail: https://github.com/cyberbotics/webots/runs/1906940169?check_suite_focus=true#logs

Feel free to edit/merge this PR.

P.S: note that the ros test is also failing during installation since a while: https://github.com/cyberbotics/webots/runs/1906940068?check_suite_focus=true

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
That's strange.
I though I fixed it in #2754 and I merged the file resulting from saving it from Webots.

**Comment by DavidMansolino** [comment]
> That's strange.
> I though I fixed it in #2738 and I merged the file resulting from saving it from Webots.

If you saved it from Webots, that is indeed strange, because the location of the `coordinateSystem` field is clearly wrong (VRML definition: https://github.com/cyberbotics/webots/blob/master/resources/nodes/WorldInfo.wrl#L5-L20) and the test suite seems to save it differently from you (maybe you didn't select all the lines when committing?).

**Comment by lukicdarkoo** [comment]
How did the tests pass:
https://github.com/cyberbotics/webots/runs/1872916701?check_suite_focus=true

Can we catch these errors before the nightly build?

**Comment by omichel** [comment]
Only quick tests on the source code are automatically performed with each PR. Longer and in depth tests (like "world update" and "ros tests") are done at night. We should monitor them and fix them if they fail.

**Comment by stefaniapedrazzi** [comment]
Tests can also be triggered by setting the corresponding label in the PR and not only on nightly builds. 
But we are rarely running the tests.

**Review by lukicdarkoo — APPROVED** [review]
Thank you!

**Pull request merged**
