### PR TITLE
Fix not updated PROTO.

### PR DESCRIPTION
**Pull request by DavidMansolino**
**Description**
The backward compatibility feature was not working on these PROTO files because the header version was preventing the backward compatibility mechanism.

**Related Issues**
This pull-request fixes issue #1896

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
The test suite is less problematic because the headers are not updated and therefore the backward compatibility mechanism works fine in those cases.

**Comment by stefaniapedrazzi** [comment]
> The test suite is less problematic because the headers are not updated and therefore the backward compatibility mechanism works fine in those cases.

Yes, I agree.
But it would be better if the test format is up-to-date and we are not using old nodes or fields format.

**Comment by DavidMansolino** [comment]
I completely agree, there is a lot of 'old' stuff in the test suite (old field format, old appearance, etc.) and this is very bad because it does not represent/test the current state of Webots :disappointed:

**Pull request merged**
