### PR TITLE
Merge revision to develop

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Merge revision to develop
- [x] Fix heavy conflicts in `dependencies/Makefile.mac/linux`
- [x] Update MD5 for the develop packages
    - [x] mac
    - [x] linux
    - [x] ~~windows~~ *None*

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍 ✔️

**Comment by stefaniapedrazzi** [comment]
Can I add the latest changed to revision in this PR too?

**Comment by stefaniapedrazzi** [comment]
otherwise I will create a new PR

**Comment by fabienrohrer** [comment]
Please don't :-) It takes more than one hour to run the distribution test. Creating a second PR after this will be more efficient ;-)

**Comment by stefaniapedrazzi** [comment]
Ok.

**Pull request merged**
