### PR TITLE
Add namespace to Ros Nodehandle and remove redundant robot name prefixes from Ros service and topic names

### LINKED ISSUE #4086: Spawning multiple ROS Controllers
**Describe the Bug**
In order to run multiple robots in the same simulation, we need to spawn separate ROS Controllers for each robot. But current implementation does not support this.

ROS Nodehandle does not have a namespace, as seen below.   
https://github.com/cyberbotics/webots/blob/2013407c7146b7bad7113572beaae2aea7eef25b/projects/default/controllers/ros/Ros.cpp#L179

And controller_manager uses this Nodehandle to advertise its services.
https://github.com/cyberbotics/webots/blob/2013407c7146b7bad7113572beaae2aea7eef25b/projects/default/controllers/ros/highlevel/RosControl.cpp#L23

Therefore, no matter what robot name is set, all controller_managers advertise their services under same names:
```
/controller_manager/list_controller_types
/controller_manager/list_controllers
/controller_manager/load_controller
/controller_manager/reload_controller_libraries
/controller_manager/switch_controller
/controller_manager/unload_controller
```

And since robots dont have their own `/controller_manager/load_controller` services, they can not spawn their own controllers.

**Steps to Reproduce**
1. Add a robot and give a name to it
2. Select ros controller and set use-ros-control parameter
3. Spawn ROS Contoller
4. Add another robot and give another name
5. Select ros controller and set use-ros-control parameter
6. Spawn ROS Contoller

**Expected behavior**
Each robot has its own ROS Controller in their own namespaces. 

**System**
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: NVIDIA GeForce RTX 2060 6 GB

**Additional context**
Setting robot name as namespace will solve this issue:
```
mNodeHandle = new ros::NodeHandle(mRobotName);
```

This will also simplify code because we won't have to manually put robot name into topics and services, like this:
https://github.com/cyberbotics/webots/blob/2013407c7146b7bad7113572beaae2aea7eef25b/projects/default/controllers/ros/Ros.cpp#L186

This line would be:

```
mTimeStepService = mNodeHandle->advertiseService("robot/time_step", &Ros::timeStepCallback, this);
```

And if we agree, i can send PR for this issue.

### PR DESCRIPTION
**Pull request by CumaOzavci**
**Description**
Replacement for #4091, into  `develop` branch instead of `master`

**Related Issues**
This pull-request fixes #4086

**Tasks**
Add the list of tasks of this PR.
  - [x] Add namespace to Ros Nodehandle
  - [x] Remove redundant robot name prefixes from Ros service and topic names
  - [ ] Test/change `webots_ros`

**Additional context**
Your `develop` branch did not include this commit: 1322a5ed172f94d5c175cd4d7a2f926153e240a7 from `master`. To avoid future conflicts i included this commit too.

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
This looks very good, thanks.

However, some webots_ros examples don't work with this change (e.g. the Pioneer example). The robot_state_publisher node struggles to find the /robot_description parameter.

**Comment by CumaOzavci** [comment]
@lukicdarkoo 

> However, some webots_ros examples don't work with this change (e.g. the Pioneer example). The robot_state_publisher node struggles to find the /robot_description parameter.

This is correct. `webots_ros` examples need to be changed too.

>I did some tests in cyberbotics/webots_ros#102 and I believe it would be nice to be able to avoid topic prefixes.

I did not add topic prefixes, i solved the prefix inconsistency issue. You already gave prefix to all sensor topic and service names. I just changed the way you gave them. 

> It would simplify single robot simulations.

If we really want to simplify single robot simulations this way, we should just get rid of all prefixes like the ones below:
https://github.com/cyberbotics/webots/blob/85016b29383660d415ceffd7bd4c644357827c12/projects/default/controllers/ros/Ros.cpp#L194-L200

**Comment by lukicdarkoo** [comment]
> I did not add topic prefixes, i solved the prefix inconsistency issue. You already gave prefix to all sensor topic and service names. I just changed the way you gave them.

I know, that's great, but since we are changing the API we can use the opportunity to allow an empty string prefix.

**Comment by CumaOzavci** [comment]
> I know, that's great, but since we are changing the API we can use the opportunity to allow an empty string prefix.

Maybe we can create a new parameter for ROS namespace. That way we can keep apart ROS namespace from robot name.

**Comment by lukicdarkoo** [comment]
@CumaOzavci Can we use `mNodeHandle = new ros::NodeHandle(mRobotName);` if robot name is present and `mNodeHandle = new ros::NodeHandle;` otherwise?

**Comment by CumaOzavci** [comment]
@lukicdarkoo, i made changes you requested.

Now if robot name is not given, ros node will not have a namespace.
`webots_ros` launch and wiki files still need to be updated.

**Comment by lukicdarkoo** [comment]
@CumaOzavci I missed your comment, thank you, I will review this tomorrow.

**Review by lukicdarkoo — CHANGES_REQUESTED** [review]
Works well, but we still have an issue with frame_id prefixes. If the robot name is not set then there should not be a prefix. Also, make sure that documentation on the following page is updated:
https://cyberbotics.com/doc/guide/using-ros

**Comment by CumaOzavci** [comment]
@lukicdarkoo 

> Works well, but we still have an issue with frame_id prefixes. If the robot name is not set then there should not be a prefix.

I fixed this issue. 

> Also, make sure that documentation on the following page is updated:
https://cyberbotics.com/doc/guide/using-ros

After we are done with source code, i can change documentation and `webots_ros` package.

**Comment by lukicdarkoo** [comment]
Thank you for this, it works nicely! We are now able to simplify example controllers:
https://github.com/cyberbotics/webots_ros/pull/102/files

@CumaOzavci  Please make sure to update documentation before merging

**Comment by BenjaminHug8** [comment]
@CumaOzavci Could you please update the documentation and fix the conflicts in order to merge this PR?

**Comment by CumaOzavci** [comment]
@BenjaminHug8,

Sorry for late reply. I was on short vacation.
I resolved the merge conflict and updated documentation

**Review by BenjaminHug8 — APPROVED** [review]
Thank you!

**Review by BenjaminHug8 — CHANGES_REQUESTED** [review]
I just noticed that this PR (https://github.com/cyberbotics/webots_ros/pull/102) should be reviewed too.

This PR should be ok but I just want to test the other PR before merging this one!

**Review by BenjaminHug8 — APPROVED** [review]
It is all good, this PR can be merged!

**Comment by CumaOzavci** [comment]
@omichel, i updated my branch and it passed from all checks.

Should i merge?

**Comment by omichel** [comment]
> Should i merge or wait for you to do that?

Yes, please merge it.

**Comment by Fran-FC** [comment]
Nice feature! Do you know when this change will be merged to the master branch? Thanks

**Comment by omichel** [comment]
> Nice feature! Do you know when this change will be merged to the master branch? Thanks

I should be merged by the end of June when we release Webots R2022b.

**Pull request merged**
