### PR TITLE
Fix dialog popup opening/closing

### PR DESCRIPTION
**Pull request by ad-daniel**
**Description**

Fixes https://github.com/cyberbotics/webots/issues/5493

### CODE REVIEW

**Comment by ad-daniel** [comment]
I believe I found the source of the problem, basically the conflict arises when doing the [finalize](https://github.com/cyberbotics/webots/blob/48444fa1f9d6213ef6efc0f69f63dbbd13db692f/src/webots/engine/WbSimulationWorld.cpp#L105) step during the loading.

At this step the pop up is supposed to display the progress with respect to the finalization process (create WREN objects, create ODE objects, etc), meanwhile as the ImageTextures/Mesh nodes are finalized, their corresponding Downloader is destroyed, which triggered the destruction of the popup progress (hundreds of times, one for each instance), which doesn't seem necessary since at this point the download is complete anyway (hence why this one kept saying progress was 100).

Removing this progress update in the Downloader destroyer removes the flickering and doesn't appear to have side effects.

**Comment by ad-daniel** [comment]
Note: the flickering is visible only in distrib mode, with a sufficiently complex world (like panda) and with cache cleared

**Comment by ad-daniel** [comment]
Actually there might be a side effect in case of a download failure (line above), then perhaps the update should take place in that specific case. I'll test it quickly, will put the PR back to draft for a moment

**Review by omichel — DISMISSED** [review]
Thank you.
I confirm the problem is fixed on macOS.

**Comment by ad-daniel** [comment]
This approach does indeed seem more appropriate as if the count changes due to unfinished downloads, the progress bar should reflect the change.

**Review by omichel — APPROVED** [review]
That seems better indeed.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Pull request merged**
