### PR TITLE
Better reload/reset table

### PR DESCRIPTION
**Pull request by omichel**
This PR tries to make the supervisor reload/reset/etc. table easier to read:
https://cyberbotics.com/doc/reference/supervisor?version=fix-make-table-easier-to-read

### CODE REVIEW

**Review by BenjaminDeleze — APPROVED** [review]
I am not totally convinced that the changes improve the readability but they are correct.

**Comment by omichel** [comment]
> I am not totally convinced that the changes improve the readability but they are correct.

If they don't improve readability, we should not merge this PR.

**Comment by omichel** [comment]
@ygoumaz, @ad-daniel and @stefaniapedrazzi: what do you think?

**Comment by ygoumaz** [comment]
Maybe centering the text in merged cells may look better, but hard to tell without trying.

**Comment by omichel** [comment]
> Maybe centering the text in merged cells may look better, but hard to tell without trying.

Done.

**Comment by ygoumaz** [comment]
It is indeed better imo.

**Comment by stefaniapedrazzi** [comment]
I'm not sure either that the readability is better than before.
I have the feeling that it is even more difficult to understand what is the title of the column by merging all these cells.
I find it easier in the previous version to understand the meaning of the 6 columns.

**Comment by stefaniapedrazzi** [comment]
If it would be possible to add some borders between columns in the header row, then probably it will be much better.

**Comment by omichel** [comment]
I just added header columns, vertical centering and colors... Is that better?

**Comment by stefaniapedrazzi** [comment]
Yes, I think it is better like this.

**Review by BenjaminDeleze — APPROVED** [review]

**Pull request merged**
