### PR TITLE
Fix crash Matlab controller

### PR DESCRIPTION
**Pull request by mael25**
**Description**
The MATLAB controllers crash in the _develop_ branch, because they fail to load `lib/controller/libgeneric_robot_window.so`  from `resources/projects/plugins/robot_windows/generic/libgeneric.so`.

**Related Issues**
This pull-request fixes issue #2996.

**Tasks**

- [x] Compatibility MacOS
- [x] Compatibility Windows

**Additional context**
This has been solved by adding `lib/controller` in the rpath of `libgeneric.so`.

### CODE REVIEW

**Comment by mael25** [comment]
Note: I had to add the lines after `include $(WEBOTS_HOME_PATH)/resources/Makefile.include`, otherwise the `OSTYPE` was not set yet to `linux`.

**Comment by stefaniapedrazzi** [comment]
> Note: I had to add the lines after include $(WEBOTS_HOME_PATH)/resources/Makefile.include, otherwise the OSTYPE was not set yet to linux.

It seems wrong to set it after including `Makefile.include` and it would be better to set `LIBRARY` before.

You can retrieve the OSTYPE in the Makefile even before the include.
See for example: https://github.com/cyberbotics/webots/blob/master/projects/samples/devices/controllers/lidar/Makefile

**Comment by stefaniapedrazzi** [comment]
We should probably also check that it works properly on Windows and macOS.

**Comment by mael25** [comment]
> > Note: I had to add the lines after include $(WEBOTS_HOME_PATH)/resources/Makefile.include, otherwise the OSTYPE was not set yet to linux.
> 
> It seems wrong to set it after including `Makefile.include` and it would be better to set `LIBRARY` before.
> 
> You can retrieve the OSTYPE in the Makefile even before the include.
> See for example: https://github.com/cyberbotics/webots/blob/master/projects/samples/devices/controllers/lidar/Makefile

Right, in fact only `resources/Makefile.os.include` is needed before, I have updated the code.
I will also test on Windows afterwards.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you

**Comment by stefaniapedrazzi** [comment]
Is something still missing or is it possible to merge this PR?

**Comment by mael25** [comment]
> Is something still missing or is it possible to merge this PR?

I have not tested on MacOS and Windows yet...

**Review by omichel — APPROVED** [review]
Thank you for the tests!

**Pull request merged**
