### PR TITLE
Bump the Qt version from 6.4.3 to 6.5.3.

### PR DESCRIPTION
**Pull request by brettle**
**Description**
6.4.3 is no longer supported, while 6.5.3 is the latest LTS release and is supported through 31 Mar 2026.

For this to work, the precompiled binaries at https://cyberbotics.com/files/repository/dependencies/ will need to be updated but I don't think I have the ability to do that.

**Tasks**
Add the list of tasks of this PR.
  - [X] Update the [changelog](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md)

### CODE REVIEW

**Comment by omichel** [comment]
I believe the instructions are [here](https://github.com/cyberbotics/webots/wiki/Qt-compilation#qt-pre-compiled-binaries). Once you have compiled a package, please let me know and I will upload it to the cyberbotics web site. Alternatively, you could decide to move this elsewhere. Maybe on GitHub? That would be more convenient for upcoming maintenance.

**Comment by brettle** [comment]
> I believe the instructions are [here](https://github.com/cyberbotics/webots/wiki/Qt-compilation#qt-pre-compiled-binaries). Once you have compiled a package, please let me know and I will upload it to the cyberbotics web site. 

Yeah, I'd found that and used it to create a precompiled package for my local linux install, but haven't done something similar for MacOS yet.

> Alternatively, you could decide to move this elsewhere. Maybe on GitHub? That would be more convenient for upcoming maintenance.

Looks like Qt6 is available via package management systems for everything we care about except Ubuntu 20.04 and that only has another 7 months of support. Could we switch to using homebrew for MacOS, apt for Ubuntu 22.04, and then for Ubuntu 20.04 use [aqtinstall](https://github.com/miurahr/aqtinstall)?

On a related note, it looks like many of the dependencies that are currently downloaded from cyberbotics.com are now available via the various package managers. Are you open to PRs which update the install scripts to get those dependencies via the package managers instead?

**Comment by omichel** [comment]
Yes, I would be happy to get rid of the dependencies hosted at cyberbotics.com, as long as the dependencies are downloaded from a stable source.

**Comment by brettle** [comment]
This PR only addresses Qt and is now ready for review. A few notes:

1. Ubuntu 22.04 ships with Qt 6.2 and we need at least 6.4 and the goal of this PR is to get to 6.5.3. As a result, I'm using aqt to install Qt on Ubuntu 22.04 in addition to Ubuntu 20.04.
2. The Qt that aqt installs requires openssl3. Ubuntu 22.04 openssl package is 3.x so we install that as a  compilation dependency and then copy the libs into webots and all is good. Ubuntu 20.04 doesn't provide openssl 3.x so we build the current latest LTS version of openssl 3.x from source and copy the libs from that build into webots. Building from source requires the perl and libtext-template-perl packages, so they are now compilation deps. The configuration used for that build is based on the the configuration that is used to build the 22.04 openssl3 package.
3. The Qt that aqt installs requires libxcb-cursor0 so I've added it as a runtime dependency. Should that lib be copied into webots as well?
4. On macos, although homebrew provides Qt 6.7, it has a bunch of dependencies. I thought that would make it challenging to copy what was needed into Webots so I opted to use aqt to install Qt. That is much closer to the existing approach so it should be less likely to cause breakage.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
